### ISSUE TITLE
Scoping related issues during rename

### ISSUE THREAD

**Issue by KasperJanssens** [carymrobbins/intellij-haskforce#104]
* Renaming the qualified import doesn't rename the invocations (if you have import qualified AA as A, and you invoke a function A.f somewhere and then try to rename A to B, the invocation isn't renamed
* Renaming a module will also rename a data constructor which has the same name in the module, for one reason or another.

**Comment by KasperJanssens** [comment]
Most of these should be covered now in the after merging in the module references branch. Will make new ones in case I encounter some

**Comment by ciez** [comment]
renaming a function does not change the function name in the exported function list e.g.

module A (funB) where -- original name stays

funB_renamed
