### ISSUE TITLE
Parser doesn't accept # as an operator

### ISSUE THREAD

**Issue by bmjames** [carymrobbins/intellij-haskforce#106]
I'm seeing an error from the parser when it encounters an operator named `#`:

![image](https://cloud.githubusercontent.com/assets/21567/5565142/65c2f452-8edf-11e4-8d83-5be222816a22.png)

**Comment by bmjames** [comment]
I can confirm this now works for me, thanks!

**Comment by carymrobbins** [comment]
Thanks @bmjames!  I'll hold off on closing this until the next release.
