### ISSUE TITLE
Invalid tool paths on Windows if the same tool is found in more than one place

### ISSUE THREAD

**Issue by bmjames** [carymrobbins/intellij-haskforce#109]
The Windows `where` command, unlike `which`, will show *all* matching files, not just the first one it encounters. (Annoyingly there's no option to make it show only the first.)

So for example, if I look for `hlint` on my Windows machine, it gives me the following output:

    F:\intellij-haskforce>where hlint
    C:\Users\Ben\bin\hlint.exe
    C:\Users\Ben\AppData\Roaming\cabal\bin\hlint.exe

When HaskForce executes this command it smashes all the lines of output together, giving the following path for my `hlint` executable:

    C:\Users\Ben\bin\hlint.exeC:\Users\Ben\AppData\Roaming\cabal\bin\hlint.exe

**Comment by carymrobbins** [comment]
@bmjames - Thanks for finding and knocking this one out!

Note that github does some commit message parsing, so it interprets `fix #issue` as an indication to close the issue.  I like to use `refs #issue`, that way all commits related to an issue are associated accordingly, but no changes will be made.  No big deal at all, just FYI.

**Comment by bmjames** [comment]
@carymrobbins I hadn't realised that about "fix", I'll use "refs" in future, thanks for pointing that out.
