### ISSUE TITLE
GHC-modi error on startup, not restartable

### ISSUE THREAD

**Issue by NobbZ** [carymrobbins/intellij-haskforce#118]
Hi there!

On startup of HaskForce I get the following:

```
13:16:18 ghc-modi error
         Killing ghc-modi due to process failure.
         You can restart it using Tools > Restart ghc-modi
         Executing ghc-modi command 'check /home/user/projects/foo/lib/Aar/AST.hs' failed with error: NG BUG: GMEIOException /home/user/projects/foo/dist/setup-config: hGetContents: invalid argument (invalid byte sequence)
         Configure (show balloon)
```

I'd like to restart ghc-modi, but the `Tools`-menu doesn't have an `Restart ghci-modi`-entry.

Contents of `lib/Aar/AST.hs`:

```
module Aar.AST where

-- | The Abstract Syntax Tree
data AST = Import  !String !(Maybe String) -- ^ Importing the module specified by the first `String`, it is always fully
                                           --   qualified. The `(Maybe String)` does save an optional qualification alias.
         | FunCall !String ![AST] -- ^ Call the function with its arguments
```

Compiling the project on the command-line works flawlessly.

Also just for completeness:

```
$ ghc-mod --version
ghc-mod version 5.2.1.1 compiled by GHC 7.8.3

$ ghc-modi version
ghc-modi version 5.2.1.1 compiled by GHC 7.8.3

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.3

$ cabal --version
cabal-install version 1.22.0.0
using version 1.22.0.0 of the Cabal library 
```

Haskforce Version: v0.3-beta.18
IntelliJ IDEA 14.0.2

**Comment by carymrobbins** [comment]
This seems like a conflict between the version of Cabal you are using and ghc-mod.  If you want to use Cabal 1.22, you'll need to also have GHC 7.10.  See https://github.com/kazu-yamamoto/ghc-mod/issues/417

**Comment by NobbZ** [comment]
What a pity. Also it seems that I destroyed my haskell in general by trying to update ghc… Even when I try to go back I can't install any package from hackage… It seems that I have to completely rebuild my haskell stack now.

**Comment by carymrobbins** [comment]
Oh no!  Sorry to hear about that.  Hopefully you've been able to get things resolved.  I've had issues in the past with using GHC HEAD and Cabal and the best solution was just resorting back to the latest GHC release.

Once ghc-mod supports Cabal 1.22 it should integrate seamlessly with HaskForce.  If you encounter any other issues feel free to report them so we can get them resolved.

Good luck on fixing your Haskell stack!
