### ISSUE TITLE
Highlight `mdo` when `RecursiveDo` is enabled

### ISSUE THREAD

**Issue by PkmX** [carymrobbins/intellij-haskforce#120]
`mdo` should be highlighted as a keyword like `do` and `data` when the `RecursiveDo` extension is enabled.

**Comment by PkmX** [comment]
... and the `rec` keyword that is enabled with `RecursiveDo`/`DoRec` extensions as well.

**Comment by carymrobbins** [comment]
I think it's reasonable enough to highlight `mdo` and `rec` as reserved words all of the time.  We could go the route of inspecting the file's pragmas, but then we'd also need to check the Cabal file's extensions as well, and it just get's more complicated from there.

The commit referenced above simply adds these as reserved words to the standard highlighting scheme.  It should be available in the next release.

**Comment by PkmX** [comment]
Thanks. I just noticed that `forall` is not highlighted either, maybe we should add them all? Is there a list of all keywords that can be enabled by extensions?
