### ISSUE TITLE
Renaming names with primes dosn't work

### ISSUE THREAD

**Issue by NightRa** [carymrobbins/intellij-haskforce#122]
Renaming ```foo'``` to ```foo``` doesn't catch the uses of ```foo'``` 
While renaming ```foo``` to ```foo'``` works well.

**Comment by carymrobbins** [comment]
Thanks for the report @NightRa, but unfortunately I haven't been able to reproduce this.  Could you give a more specific example?  For instance, this worked for me -

```
foo' = undefined
bar = foo'
```

Renaming either the declaration or the usage of `foo'` still results in a proper refactor.  I am currently using `Shift+F6` for rename refactoring.

**Comment by NightRa** [comment]
```
func foo' = foo' + 1
```

**Comment by carymrobbins** [comment]
Ah ok.  That has to do with reference resolve of function arguments, which isn't currently implemented.  That should be completed fairly soon as there is currently a pull request that supports at least some of that.  Note that rename refactoring of function arguments shouldn't work regardless of the prime.

**Comment by NightRa** [comment]
@carymrobbins It works for simple names currently..
Thanks!

**Comment by carymrobbins** [comment]
The local variable reference resolve implemented by @KasperJanssens in #148 has resolved this issue.  You should see it in the next release, v0.3-beta.20.
