### ISSUE TITLE
Cabal 1.22 and ghc-modi incompatibilities

### ISSUE THREAD

**Issue by NightRa** [carymrobbins/intellij-haskforce#124]
I get the following error on startup:
Executing ghc-modi command 'check C:/Users/ilan3_000/Programming/AI/Furniture/src/Model.hs' failed with error: NG BUG: GMECabalFlags (GMEString "extractField: failed extracting configFlags from input, input contained `configFlags'? False")

It fails with both ghc-modi versions: 5.1.1.0 and 5.2.1.2

The code I'm working on is here:
https://github.com/NightRa/FurnitureAI

See also:
http://stackoverflow.com/questions/27943929/intellij-haskell-plugin-ghc-modi-failed-with-error

**Comment by NightRa** [comment]
Also, I can't find the ```Tools > Restart ghc-modi``` the error is suggesting to try. (does it even exist?)

**Comment by NightRa** [comment]
Seems to be duplicate of https://github.com/Atsky/haskell-idea-plugin/issues/77.
```cabal clean``` doesn't solve the issue.
After lots of hours, I figured out it's because I upgraded to cabal-1.22

**Comment by NightRa** [comment]
Now it fails with ```Executing ghc-modi command 'browse -d Prelude' failed with error: Failed to write command to ghc-modi: ```

**Comment by carymrobbins** [comment]
Does ghc-mod(i) work from the command line?  This sounds like a cabal conflict.  Also, I'm not sure that ghc-mod fully supports cabal 1.22 yet.  See https://github.com/kazu-yamamoto/ghc-mod/issues/417

**Comment by DanielG** [comment]
@NightRa Can you still reproduce this bug? If you can could you upload a copy of the `dist/setup-config` file somewhere so I can figure out why you're getting this particular failure mode?

**Comment by NightRa** [comment]
@DanielG It's an incompatability with cabal 1.22.
I downgraded to 1.21 and everything is working again. 
Downgrading cabal on windows was extremely painful and took me half a day, so I'd rather not retry to upgrade to cabal 1.22 any time soon.
Is there a way to isolate the cabal update completely somehow so that it doesn't damage my previous setup?

**Comment by DanielG** [comment]
In theory but I don't want to cause you more pain.

I'll come around to setting up some windows VMs for testing at some point ;)

**Comment by THeK3nger** [comment]
I have the same problem and cabal 1.22. 

This is the dist/setup-config file. https://www.dropbox.com/s/fki0pv4vjkdjwx7/setup-config_copy?dl=0

Maybe I can help before downgrading to 1.21 too. :)

**Comment by carymrobbins** [comment]
@NightRa, @THeK3nger - This issue should be resolved upstream via ghc-mod now.  If anyone still experiences this issue, please reopen.
