### ISSUE TITLE
ghc on osx

### ISSUE THREAD

**Issue by fatlazycat** [carymrobbins/intellij-haskforce#125]
Am trying to use http://ghcformacosx.github.io

How is haskforce trying to find ghc ? via the path ?

Am getting 

16:45:50 ghc-modi error
         Killing ghc-modi due to process failure.
         You can restart it using Tools > Restart ghc-modi
         Executing ghc-modi command 'check /Users/graham/Development/BitBucket/haskell/helloworld/src/Main.hs' failed with error: NG BUG: GMEIOException user error (ghc not found)

**Comment by carymrobbins** [comment]
ghc-mod itself seems to use the path, even though there is a command line argument to pass it the path to ghc.  Unfortunately, last time I tried to get this to work with the command line argument it didn't seem to make a difference and I had to hack around with the PATH.  I'll dig in and figure out a good way to handle this.  Ideally, HaskForce should be using the GHC SDK to find the path.

**Comment by levinotik** [comment]
:+1:

**Comment by carymrobbins** [comment]
Looks like ghc-mod just implemented the ability to pass in the path to the ghc executable -

https://github.com/DanielG/ghc-mod/commit/75fa3d4f2661182c5e1908a7efce11215308fa6d

Once this gets in the next ghc-mod release I'll get it wired up in HaskForce.

**Comment by carymrobbins** [comment]
On second thought, I'll just go ahead and provide some hacks to the PATH variable so this should work.  It's not pretty, but does the job.  In the next release, this issue should be resolved.  Eventually I'll probably explicitly pass in the `--with-PROG` parameters, but unfortunately it seems that ghc-modi refuses to work at all when those are provided.

**Comment by agrafix** [comment]
I have the same issue, looking forward to the fix :+1:

**Comment by carymrobbins** [comment]
@agrafix @levinotik @fatlazycat - The latest release is out and should cover this issue.  Please let me know if you experience any other issues like this.  Thank you!
