### ISSUE TITLE
Type Information doesn't play nice with line wraps

### ISSUE THREAD

**Issue by KasperJanssens** [carymrobbins/intellij-haskforce#126]
I suppose the wrong coordinates in the file are used, there are likely coordinates that take line wraps into account. Right now, the behavior is that the type info returns the type information from the correct column but from the wrong line, can be a bit weird. Will try to fix this.

**Comment by carymrobbins** [comment]
I wonder if this is related to this GHC bug: https://ghc.haskell.org/trac/ghc/ticket/4150

**Comment by KasperJanssens** [comment]
Hmm, not sure. There doesn't seem to be a problem with multi line comments for example.

**Comment by carymrobbins** [comment]
@KasperJanssens - Closing for now as I haven't experienced any issues with this.  If there are some specific examples that you know of, feel free to share (although, I realize it's been quite a while since this was originally submitted).  We can reopen if need be.
