### ISSUE TITLE
ghc-modi error

### ISSUE THREAD

**Issue by grguthrie** [carymrobbins/intellij-haskforce#127]
(New user) - I was not getting any of the nice GUI features (autocompletion, ..) and someone pointed out I needed to install ghc-mod (as per the instructions!), but now I get this error:
"ghc-modi error
Killing ghc-modi due to process failure. You can restart it using Tools > Restart ghc-modi Executing ghc-modi command 'check D:/Projects/Heat/HaskellDemo/src/PowerSet.hs' failed with error: NG BUG: GMECabalFlags (GMEString "extractField: failed extracting configFlags from input, input contained `configFlags'? False"):

**Comment by carymrobbins** [comment]
What version of cabal and ghc-mod are you using?  This sounds like a conflict between cabal and ghc-mod.  See https://github.com/kazu-yamamoto/ghc-mod/issues/417 for more info.

**Comment by BeCalmedAgain** [comment]
(New User) - Apologies if this is in the wrong place but the closest I could find that might help.

Linux Mint install and installed all the haskell stuff but for the life of me ghc-modi is not installed, apt-get ghc-mod refers to Happy Haskell programming on Emacs. 

I can find ghc-modi under ~/.cabal/bin/ghc-modi but nothing has been copied/link to /usr/bin

Trying to get Atom with ide-haskell working

Ideas??

**Comment by carymrobbins** [comment]
@BeCalmedAgain - Well, you could always try out HaskForce as an alternative. :)

Joking aside, you'd probably want to ask the question on the atom bug tracker instead.

**Comment by carymrobbins** [comment]
@grguthrie - I'm going to go ahead and close this; please reopen if you are still experiencing the issue and it is not related to the cabal conflict I referenced.

**Comment by grguthrie** [comment]
Ok. thanks.
