### ISSUE TITLE
Improve SDK and run configurations

### ISSUE THREAD

**Issue by carymrobbins** [carymrobbins/intellij-haskforce#128]
The SDK and run configuration setup can be a little complicated.  Let's figure out how to make this simpler and more intuitive for a new user.

**Comment by carymrobbins** [comment]
@grguthrie described the following situations in #31 -

> Thanks. It is a very simple project - basically a "Hello World" demo to try this IDE for Haskell.
> I tried your suggestion, but it did not seem to find the files (cabal, .hs), so I started a new project - and it complains:
> Cannot start compiler: the SDK is not specified for module "PowerSet".
> Specify the SDK at Project Structure dialog.

This sounds like you attempted to use *Open Project* instead of *New Project*.

And also -

> I started a new project. Added my test program Demo.hs, and a Main.hs that imports and calls a function in Demo. It seems to build OK, but how do I run it? The executable is in dist/build/Demo/Demo.exe, but run asks for a configuration, and if I chose Haskell Application, it doesn't seem to allow one to actually run (grayed out). I am not sure what is different now, or how to proceed.

A couple of things here.

First, it seems that the SDK field is missing when you go to create a new project.  For now, you'll need to setup the SDK manually by going to **File > Project Structure > Project SDK > New... > Haskell SDK**.  It should find the path to your GHC installation automatically.  If not, just choose the parent folder that contains the GHC `bin` and `lib` directories.

Next, our build and run tasks utilize Cabal.  You will need to have a cabal project file.  To generate a simple one, you can, via the command line, `cd` to your project directory and run `cabal init`.  It will interactively ask you for various info to setup your project accordingly.  I'd like to eventually have HaskForce do this for you.

Once you have the SDK setup and the Cabal file created, you should be able to use the run configurations as normal.

**Comment by grguthrie** [comment]
Thank you.

Yes, I had moved the project to a new location, so then I tried to just Open it there. Failing that, I did the New Project approach as described.

I did now add the GHC as SDK to the project options. Everything reports that it builds fine, but actually the .exe is old, and a new one is not being built. If I edit the Main.hs, and do a build, it reports success, but no new .exe is generated.
Even for that one (dist/build/Pgm/Pgm.exe) Run brings up the edit configurations, and now the Run button is alive – but clicking it doesn’t seem to do anything. And clicking the Defaults options dims the Run button, and choosing Haskell Application there still does not seem to give anything that will run.

Should Run just Run, or should it bring up the Edit-configurations pop-up every time?

Sorry to be missing something simple here!

(I do already have a cabal file.)

name: PowerSet
version: 0.0.1
cabal-version: >=1.2
build-type: Simple
license: AllRightsReserved
synopsis: Simple Demo
data-dir: ""

executable PowerSet
    build-depends: base -any
    main-is: Main.hs
    buildable: True
    hs-source-dirs: src
   other-modules: PowerSet.hs

-------------------------------------------
-------------------------------------------

**Comment by carymrobbins** [comment]
@grguthrie: To create a run configuration, go to **Run > Edit Configurations**, click the `+` button on the top-left, choose **Haskell Application**, give it a name and click **OK** to save it.

However, it seems that the initial compiler settings aren't getting saved.  This is a bug, which I will resolve.  To get around this for now, just go into **Preferences > Build, Execution, Deployment > Compiler > Haskell Compiler**.  To force a save you can, for instance, uncheck **Build with profiling information** and click **OK**.  Now your run configuration should work.

**Comment by carymrobbins** [comment]
Note, I've opened #129 to resolve this specific issue.  Also, you may have noticed the run configuration providing you an warning message in the bottom of the pane, stating something like **Failed executing cabal to check its version.**

**Comment by grguthrie** [comment]
Wonderful – thanks!

-------------------------------------------

**Comment by grguthrie** [comment]
Perfect - thanks a lot.

**Comment by carymrobbins** [comment]
@grguthrie - Heads up, there was an issue with the new project wizard in which it did not prompt for the Haskell SDK (see #141).  That is (more than likely) why you had to configure the SDK manually.  It should be resolved in the next release, v0.3-beta.20.

**Comment by carymrobbins** [comment]
You are now prompted to configure your SDK and Haskell tools via the New Project wizard, so this should be resolved in **v0.3-beta.21**.
