### ISSUE TITLE
Block comments aren't colored correctly

### ISSUE THREAD

**Issue by NightRa** [carymrobbins/intellij-haskforce#130]
Block comments, {- ... -} are colored in a white color, while they should have a grey color such as with -- comments.

**Comment by carymrobbins** [comment]
@NightRa - do you mind providing a screenshot?  You should be able to paste it into the comment.

**Comment by NightRa** [comment]
![blockcommentcolor](https://cloud.githubusercontent.com/assets/2140983/6191717/5422bbde-b3b4-11e4-8750-203ec754d28b.PNG)

**Comment by carymrobbins** [comment]
@NightRa - Closing this issue as it seems to be resolved.  Please reopen if you are still experiencing the issue.
