### ISSUE TITLE
Add an accesible button for restarting ghc-modi

### ISSUE THREAD

**Issue by NightRa** [carymrobbins/intellij-haskforce#131]
Being able to restart ghc-modi after a failure would be very valuable and time saving, instead of having to restart intllij idea many times to retry and fix issues.

**Comment by carymrobbins** [comment]
@NightRa - Actually, this does exist.  It should be under **Tools > Restart ghc-modi**.  If that menu item is not appearing for you and ghc-modi is configured correctly, that's a bug.

**Comment by NightRa** [comment]
@carymrobbins Each time I was searching inside Settings -> Tools. Just found out that's in the tools dropdown.
Thanks.
