### ISSUE TITLE
There are no features except syntax coloring

### ISSUE THREAD

**Issue by NobbZ** [carymrobbins/intellij-haskforce#138]
After I added a cabal file to the project (which was needed, to have it compile) no feature is working. No code completion, no stylish, not anything.

Before I added that cabal-file I had code completion during my quick write up of ``module Main`` for keywords, but not for functions.

Using Code-Reformatting (I guess this is the IntelliJ for applying stylish-haskell) does absolutely nothing, but the path to stylish is configured.

Also I can't find any way to invoke hlint. So I supposed it is automatically invoked and annotates code, but there are no lints for ``f x = id x``, which hlint would normally suggest to Eta-reduce into ``f = id``.

Furthermore I can't find a way to add missing type declarations. Nothing is as displayed on your animations for me.

Environment:
* IntelliJ 14.0.3
* HaskForce 0.3-beta.18 (downloaded Zip from release page and then installed from disk, since I wasn't able to find it in official repository)
* Windows 7
* ghc 7.8.3
* cabal
 * library 1.18.1.3
 * install 1.18.0.5
* HLint 1.9.13
* stylish 0.5.11.0
* /ghc-modi?/ 5.2.1.2

**Comment by NobbZ** [comment]
OK, Completion and linitng does work, but I have to go into settings and configure pathes for the tools everytime I restart IntelliJ or load another project. But no completion for Haskell-Keywords.

Stylish and type declarations still don't work.

**Comment by carymrobbins** [comment]
@NobbZ - Have you checked out the [Quick Start Guide](https://github.com/carymrobbins/intellij-haskforce/wiki/Quick-Start-Guide)?

> You can set the defaults for all projects using **File > Other Settings > Default Settings.**

**Comment by NobbZ** [comment]
OK, I've set up the defaults, seems to work for linitng and completion. But still I can't find a way to use stylish and insertion of type delcaration doesn't work too.

**Comment by carymrobbins** [comment]
For **stylish-haskell**, go to **Code > Reformat code with Stylish Haskell**.  Next to it will be the appropriate key binding for your platform.

Are you getting underline warnings for missing type signatures?

**Comment by carymrobbins** [comment]
@NobbZ - Are you still experiencing this issue?

**Comment by NobbZ** [comment]
I can't update currently due to mobile internet, I will try after the
weekend.
Am 14.03.2015 15:43 schrieb "Cary Robbins" <notifications@github.com>:

**Comment by NobbZ** [comment]
OK, today I was able to test it (finally), and it seems to work.

But allow me one last question: Is it possible to have stylish run on save or shall I open a corresponding feature request?

**Comment by carymrobbins** [comment]
I'm sure that it's possible.  Feel free to close this issue and submit a new one detailing what you are looking for.

**Comment by NobbZ** [comment]
OK then we consider this one closed.
