### ISSUE TITLE
Notes on building the plugin

### ISSUE THREAD

**Issue by d3dave** [carymrobbins/intellij-haskforce#143]
1. **Ant integration**: It isn't mentioned in the readme, but for the `Build -> haskforce` menu to show up in IntelliJ, the Ant integration plugin needs to be enabled. I had it disabled, and it took me a while to figure out why these build targets weren't showing.

    a. Also not mentioned in the readme is needing to create the `build.properties` file.
    b. The `generate.sources` target isn't listed in the menu (because of filter settings in the *Ant Build* tool window). ~~I found the target in the `build.xml` file and ran `Build -> Run Ant Target` instead~~ It can be found in the *Ant Build* tool window and run from there.

2. **JFlex support**: The plugin does not work in IDEA 14.0.3 at least.

3. Importing the project from existing sources requires overwriting the existing `.idea` directory.

~~I have managed to build the plugin, but when attempting to test, I'm getting `ClassNotFoundException`s on the `*FileTypeFactory` classes.~~

After running `generate.sources` and initiating a `Make Project` I get errors like this in all the generated files:

    Error:(864, 26) java: array required, but java.lang.CharSequence found

Any help would be appreciated.

**Comment by carymrobbins** [comment]
Hmmm, that's strange.  Currently I'm running 1.5.1, which seems to work for me.  The ant task should use the JFlex.jar in the repo, so there shouldn't be any conflicts there.

What OS and version of Java are you running?  This build works fine on Ubuntu and Mac OSX with Java 1.6.

You make some good points about the readme, I'll get those cleaned up.

**Comment by d3dave** [comment]
I'm running Windows 8.1 with Java 1.8.

**Comment by carymrobbins** [comment]
@d3dave - Sorry for the extreme delay, but I've updated the build documentation on the README.  Part of the issue may be building with JDK 8, so you might want to try JDK 6.  Once IntelliJ adopts Java 8 as it's default runtime I'll start building the plugin with JDK 8.

Feel free to let me know if you'd like the documentation better clarified.  You are also more than welcome to submit a pull request.

**Comment by carymrobbins** [comment]
@d3dave - I'm going to go ahead and close this.  Please reopen if there's more to be done here.
