### ISSUE TITLE
Enable configuring of cabal file paths in modules for ghc-mod

### ISSUE THREAD

**Issue by agrafix** [carymrobbins/intellij-haskforce#144]
The ghc-mod/ghc-modi report that certain modules can not be found. The modules are from packages that are installed in a sandbox. Where is ghc-mod run? I have multiple packages in the same Intellij Project:

    /users
       cabal.sandbox.config
       .cabal-sandbox/
       users.cabal
       src/Web/Users/Types.hs
    /users-test
       cabal.sandbox.config
       .cabal-sandbox/
       users.cabal
       src/Web/Users/Test.hs
...

**Comment by carymrobbins** [comment]
The path logic basically goes based on the module path, which is probably not the best idea.  It should really be executing from the location of your cabal file.  Just to be sure I can reproduce this and ensure it's fixed, could you tell me where your module files are located?  You can find it by running (in UNIX) -

```
find . -name "*.iml"
```

For reference, the logic which picks the ghc-mod(i) working directory is [here](https://github.com/carymrobbins/intellij-haskforce/blob/master/src/com/haskforce/utils/ExecUtil.java#L170-175).

**Comment by agrafix** [comment]
The .iml is located in the root directory:

    ./users.iml
    ./users
       cabal.sandbox.config
       .cabal-sandbox/
       users.cabal
       src/Web/Users/Types.hs
    ./users-test
       cabal.sandbox.config
       .cabal-sandbox/
       users.cabal
       src/Web/Users/Test.hs

**Comment by carymrobbins** [comment]
Ahh, so that explains it.  Yet another reason why the current logic is broken.

One way that you can get around this is by going to **Project Structure > Modules** and adding modules for each sub-project.  So you'd want a module pointing to `./users` and another one pointing to `./users-test`.

Although, a much better way is to have the IDE do this for you, possibly via an **Import Project** feature and some tighter cabal integration.

**Comment by carymrobbins** [comment]
This will be resolved in version **v0.3-beta.21**.  You can use **Tools > Discover Cabal Packages** to import packages into your project.  Sorry for the delay on this, please reopen if you continue to experience this issue.
