### ISSUE TITLE
ghc-modi integration not working in free-form project

### ISSUE THREAD

**Issue by thorinii** [carymrobbins/intellij-haskforce#149]
I created a freeform project for a Haskell/Scala project I'm working on (Haskell for the Snap app, Scala for acceptance testing). I then created modules for the two subdirectories, using the New Module -> Haskell -> "here's the sources" -> etc.

ghc-modi is not running, nor does *Restart ghc-modi* show in the Tools menu (at minimum, I'm not sure about other services). This is a bit of a pain as I like the autocomplete.

Is there anything I can do about it in IntelliJ, or does something need to be fixed in the plugin?

**Comment by carymrobbins** [comment]
Have you already configured ghc-modi in **Preferences > Other Settings > Haskell Tools**?  This might be related to #144.

**Comment by thorinii** [comment]
Ah right. I thought the options were saved globally, but it appears they're just per-project? While doing a bunch of tests I found that the settings "disappeared" between creating a new project.

**Comment by carymrobbins** [comment]
@thorinii - You can set your global settings in **File > Other Settings > Default Settings**.

This is making me think that the **New Project** dialog should walk you through setting these up.

**Comment by thorinii** [comment]
Man IntelliJ is a maze if you don't know it well :-). Thanks.

Yes that's probably a good idea. I had it working the first time I installed it, but my second project (this one) obviously wasn't. I guess that's why.
