### ISSUE TITLE
Valid binary operator --* (and similar) are shown as line comment

### ISSUE THREAD

**Issue by NobbZ** [carymrobbins/intellij-haskforce#152]
The following valid function definition is badly marked as commented:

```hs
(--*) :: Int -> Int -> Int
a --* b = (a - b) * (b - a)
```

And as you can see, `pygments` does the same mistake!

That this is indeed valid is proved by the following terminal session:

```plain
$ cat SomeTest.hs
module SomeTest where

(--*) :: Int -> Int -> Int
a --* b = (a - b) * (b - a)

$ ghci SomeTest.hs
GHCi, version 7.8.3: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
[1 of 1] Compiling SomeTest         ( SomeTest.hs, interpreted )
Ok, modules loaded: SomeTest.
*SomeTest> 1 --* 2
-1
```

From [Haskell 2010 report](https://www.haskell.org/onlinereport/haskell2010/haskellch2.html#x7-170002.3):

> ## 2.3 Comments
>
> Comments are valid whitespace.
>
 >An ordinary comment begins with a sequence of two or more consecutive dashes (e.g. --) and extends to the following newline. The sequence of dashes must not form part of a legal lexeme. For example, “-->” or “|--” do not begin a comment, because both of these are legal lexemes; however “--foo” does start a comment.

Bye the way: `vim` does highlight this one correctly.

**Comment by carymrobbins** [comment]
This should be resolved as of the next release, v0.3-beta.20.  Thanks for the report!

**Comment by NobbZ** [comment]
Is there a duedate?

**Comment by carymrobbins** [comment]
@NobbZ - I'm working on a couple of other issues.  If I can't get them resolved today I'll just go ahead and release the next version.

**Comment by carymrobbins** [comment]
@NobbZ - I just released the latest version.  If you can't wait for the IntelliJ plugin repo to update (which may take a day or so due to moderation) you can grab the latest release from here -

https://github.com/carymrobbins/intellij-haskforce/releases

**Comment by NobbZ** [comment]
It is easy to wait, this just breaks some colors, not the project ;) Also
I'm on mobile again and have to wait another 2 days until I am wired
again...

2015-03-30 11:43 GMT+02:00 Cary Robbins <notifications@github.com>:
