### ISSUE TITLE
ghc-modi problem on OS X

### ISSUE THREAD

**Issue by 0culus** [carymrobbins/intellij-haskforce#165]
Hi,

This is similar (I think) to issue #118 . I'm getting a slightly different error, however. As in that issue, however, the option to restart ghc-modi is missing from the tools menu. It is worth noting that this all works perfectly fine in Windows (where I have identical versions of everything installed.) I installed the haskell platform through MacPorts. 

```
failed with error: NG BUG: GMEProcess ["cabal","configure"] (GMEString "cabal configure (exit 1)\\ncabal: ghc: missing -B option\\n")
```

Versions of all my stuff:

![screen shot 2015-06-16 at 22 31 01](https://cloud.githubusercontent.com/assets/5642020/8199758/e84e79aa-1477-11e5-911d-38822d488a22.png)

![screen shot 2015-06-16 at 22 35 51](https://cloud.githubusercontent.com/assets/5642020/8199778/2daf2c56-1478-11e5-933a-a8dd94529be2.png)

**Comment by carymrobbins** [comment]
@0culus - Where do you see this error, and what are you doing when it occurs?

**Comment by 0culus** [comment]
@carymrobbins sorry, the notification of your comment got murdered by email spam filters. However, I since have removed the macports Haskell Platform and switched to the "official" jetbrains Haskell plugin and a standard installation of Haskell Platform.  

Basically, this would occur whenever ghc-modi tried to be called for anything at all, particularly on startup and loading a project. 

If you like, I could try to reproduce this weekend.

**Comment by carymrobbins** [comment]
@0culus - Seems like something strange going on with your configuration.  I see that you didn't have the path to your ghc set, so your SDK is probably not configured properly.

What is the path to your installed ghc?  Usually your SDK path should be directory above ghc's bin directory.

**Comment by 0culus** [comment]
@carymrobbins this is why I abandoned installing Haskell Platform via MacPorts. I tried various paths that should have been correct and they did not work. I'll reinstall it and try to replicate later.

**Comment by carymrobbins** [comment]
@0culus - Closing this for now, please reopen if there's something that needs to be addressed.
