### ISSUE TITLE
Could not find a component assignment, falling back to guessed GHC options.

### ISSUE THREAD

**Issue by ciez** [carymrobbins/intellij-haskforce#166]
when working on a new module, not yet referenced anywhere in the project, error pops up:

(!) ghc-modi error
Unable to parse problems from ghc-modi: Warning: Could not find a component assignment, falling back to guessed GHC options

Configure

**Comment by carymrobbins** [comment]
It sounds like ghc-mod is trying to figure out which cabal component to use since it can't find that module in your cabal file.  Maybe in this case we could just issue a warning that the file is not in your cabal file and thus won't get error annotations.

**Comment by ciez** [comment]
something I should have mentioned: I upgraded cabal to  1.22.2.0 and ghc to 7.10.1 this broke ghc-mod & ghc-modi so I installed those some time ago from source in main git branch.

yes, please "hide" error annotations in this case. quite a number of those errors pop up while working on a file in progress. clicking on the file makes them go away but still. ghc would catch this issue anyway ;)

Haskforce is very useful plugin. Thank you very much for it!
