### ISSUE TITLE
Possibility to use stack instead of cabal

### ISSUE THREAD

**Issue by jgoux** [carymrobbins/intellij-haskforce#167]
Hi,
would it be possible to optionally use stack instead of cabal for the build process ?

**Comment by carymrobbins** [comment]
I don't see why not.  I haven't used stack yet, but it does seem to have some pretty desirable features, such as handling your GHC install.

**Comment by 2chilled** [comment]
+1 for introducing stack support!

**Comment by wolftune** [comment]
Looking at other tickets, it seems compatibility between ghc-mod and Stack is the prereq to plugins like this working with Stack.

**Comment by carymrobbins** [comment]
Oh, that's a really good point @wolftune.  Depending so much on ghc-mod is probably not the best idea anyway, and I've been wanting to provide alternatives that would work a bit more "natively".

**Comment by wolftune** [comment]
@carymrobbins I have no idea about the issues in depending on ghc-mod, FWIW, I was looking at the ide-haskell package for Atom and noticed the same issue: it relies on ghc-mod, and ghc-mod is not yet compatible with Stack. I saw tickets in places where people were discussing this, so I have reason to suspect that ghc-mod / Stack compatibility will get worked out soon.

**Comment by carymrobbins** [comment]
Yep, it looks like there is active discussion about it in the ghc-mod issue here - https://github.com/kazu-yamamoto/ghc-mod/issues/498

Also, it's worth mentioning that folks are having trouble creating a Haskell project since the Haskell SDK requires Cabal.  Ideally, you shouldn't need Cabal to create the project, certain features should just not be available.  That also paves the way to choose your own build tool, whether it be Cabal, Stack, or vanilla GHC.

**Comment by wolftune** [comment]
@carymrobbins Stack itself relies directly on Cabal. The thing Stack replaces is *cabal-install* (which is a separate thing from Cabal the library).

**Comment by carymrobbins** [comment]
Yeah, I should be a bit more explicit.  By Cabal I was referring to cabal-install, the `cabal` command line utility.  Either way, just because you are not using a particular tool, you should still be able to use HaskForce, sans the corresponding features.

**Comment by carymrobbins** [comment]
Stack support is now in the latest release.  I will be updating the Quick Start guide, so check there for more info.
