### ISSUE TITLE
uncompleted let hangs - indents

### ISSUE THREAD

**Issue by ciez** [carymrobbins/intellij-haskforce#178]
when entering a function in let notation (pure function without do), before "in" clause is entered, the editor hangs with these symptoms:

inspection icon is a grayed-out eye (stuck in a loop?)

cursor blinks

it is not possible to enter text below the "let" block. tab key does not work. ctrl / (uncomment shortcut) does not work

enter key does not work

backspace key does not work when cursor is placed before the indented text

when "in .." line is added in external text editor, the "hang" sometimes goes away

let block indents look different in Idea editor window and the external text editor (Sublime Text)

**Comment by ciez** [comment]
tabs are turned off - already checked

**Comment by carymrobbins** [comment]
Unfortunately, I haven't been able to reproduce this.  Could you paste an example of the file content and cursor position when this happens?  Smells like a parser bug to me.

**Comment by ciez** [comment]
Will do so. It happens irregularly.
