### ISSUE TITLE
Support ghc-mod 5.4.0.0

### ISSUE THREAD

**Issue by xkrt** [carymrobbins/intellij-haskforce#182]
Error occurs on new Haskell project:
```
ghc-modi error
Unable to parse problems from ghc-modi: Warning: ghc-modi is deprecated please use 'ghc-mod legacy-interactive' instead
```

version: ghc-modi version 5.3.0.0 compiled by GHC 7.10.2

**Comment by carymrobbins** [comment]
Thanks for this, the ghc-mod stuff needs to be cleaned up anyway.  Aside from the error popup, does it still provide the error checking in the file?

**Comment by xkrt** [comment]
Not sure, because I can't add 'Haskell SDK' since I use `stack`, which enables experiments with Haskell on Windows for newbies like me :)

+1 for #167

**Comment by MasterMastic** [comment]
I have the same problem, and no @carymrobbins, it does not provide any error-checking.

**Comment by orome** [comment]
What sorts of error checking (or other behavior) should I see if ghc-mod (and ghc-modi) is working?

In the meantime, should we enter `gcc-mod` for the ghc-modi tool path, with `legacy-interactive` as options? Or should we enter nothing for gcc-modi, and put those options with the ghc-mod tool?

**Comment by carymrobbins** [comment]
@orome - That doesn't seem to work yet, see #191.  In the meantime, you can try to use an earlier version of ghc-mod(i), particularly 5.2.1.2 should work just fine.

**Comment by carymrobbins** [comment]
Finally!  We now have ghc-mod 5.4 support, as well as stack support, in the latest release.  Closing this issue, but please submit issues if you encounter any problems.

**Comment by carymrobbins** [comment]
Also note that you _may_ need to reconfigure `ghc-modi` as `ghc-mod` and have its flags set to `legacy-interactive`.  HaskForce does this automatically when you configure the tools, so you can also clear any ghc-modi configuration you may have, apply the changes, then use Auto-find and apply again to reconfigure automatically.

**Comment by WillSewell** [comment]
Good job! Thanks :)

**Comment by orome** [comment]
@carymrobbins: How will we know if we need to reconfigure `ghci-modi` as  `ghci-mod`. I don't seem to have a choice since when I apply settings the former gets changed to the latter.

**Comment by carymrobbins** [comment]
@orome - Sorry, I should have been more clear.  It _should_ change to the latter, because we want it configured as `ghc-mod legacy-interactive`.  When you are using the deprecated ghc-mod, HaskForce fixes this for you.

**Comment by orome** [comment]
I guess I don't understand the relationship between `ghci-modi` as  `ghci-mod`. Is the former or the latter deprecated? Which should I have in each of the settings to be "most current"?

**Comment by carymrobbins** [comment]
@orome - `ghc-modi` is deprecated and has been replaced by `ghc-mod legacy-interactive`.  Here's what your configuration should look like, substituting the path to `ghc-mod` with wherever you have it installed.

![image](https://cloud.githubusercontent.com/assets/3103764/11307141/ee9ce04c-8f7b-11e5-9500-2ca786b346eb.png)

**Comment by orome** [comment]
@carymrobbins — Cool. Thanks. Got it. Seems slow though.

**Comment by carymrobbins** [comment]
@orome - Feel free to open an issue if the performance is a nuisance.  Include which actions seem slow (type info, error checking, etc.) and other side effects that may be impacting your workflow (e.g. locks the editor).
