### ISSUE TITLE
Cannot create SDK

### ISSUE THREAD

**Issue by dramforever** [carymrobbins/intellij-haskforce#183]
I installed ghc 7.10.2 to `~/.ghc-bin`, but when I choose this directory it tells me "The selected directory is not a valid home for Haskell SDK"

**Comment by carymrobbins** [comment]
Wow, this is an incredibly silly bug.  We just need to fix the egregious `.endsWith("bin")` checks [here](https://github.com/carymrobbins/intellij-haskforce/blob/master/src/com/haskforce/HaskellSdkType.java#L76-76) and [here](https://github.com/carymrobbins/intellij-haskforce/blob/master/src/com/haskforce/HaskellSdkType.java#L169).  I'll get that fixed ASAP.

**Comment by carymrobbins** [comment]
@dramforever - In the meantime, you can try renaming that directory to something that doesn't end in `bin` and see if it works.  That would confirm my theory.  If it still doesn't work, maybe paste the contents of the directory (e.g. `ls -A ~/.ghc-bin`) and we can go from there.

**Comment by dramforever** [comment]
Ok thanks a lot for that.

(btw relevant xkcd http://xkcd.com/1172/ )

**Comment by carymrobbins** [comment]
Once stack support rolls out, the Haskell SDK will be automatically created for you and require virtually no configuration.  This applies to cabal-based projects as well.  Thus, this will become a non-issue.
