### ISSUE TITLE
Unable to parse problems from ghc-modi: cabal-helper-wrapper.exe: ghc: readCreateProcess: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by mrkafk** [carymrobbins/intellij-haskforce#191]
I'm trying to configure HaskForce plugin into IntelliJ IDEA (Community Edition 14), latest HaskForce plugin. 

I configured "ghc-mod" (mod, not modi) with "legacy-interactive" in "GHC Modi" `Flags`. The root problem seems to be related to cabal version, although when I try autocompleting on any Haskell symbol, I get this:

	ghc-modi error
			   Unable to parse problems from ghc-modi: cabal-helper-wrapper.exe: ghc: readCreateProcess: does not exist (No such file or directory)

			   ghc-mod: readCreateProcess: C:\ACME\projects\htest\.cabal-sandbox\cabal-helper-0.5.3.0-553kah86RQN6BuDX6XLBiX\cabal-helper-wrapper.exe "C:\\ACME\\projects\\htest" "C:\\ACME\\projects\\htest\\dist" (exit 1): failed

When I run this last command (`C:\ACME\projects\htest\.cabal-sandbox\cabal-helper-0.5.3.0-553kah86RQN6BuDX6XLBiX\cabal-helper-wrapper.exe "C:\\ACME\\projects\\htest" "C:\\ACME\\projects\\htest\\dist"`), it tries to install cabal 1.18:

    cabal-helper-wrapper.exe: Installing Cabal version 1.18.1.3 failed.

I already have cabal, of version 1.22 (installed via Haskell Platform v7.10.2-a, released recently in August).

**Comment by carymrobbins** [comment]
Duplicated by #182.  Until ghc-mod 5.4 support is added, you can work around this by using ghc-mod 5.2.1.2.

**Comment by carymrobbins** [comment]
@mrkafk - It seems that this issue is actually a problem with installing ghc-mod.  You may want to try building it from source with stack or using a cabal sandbox.
