### ISSUE TITLE
ghc-mod running in wrong directory

### ISSUE THREAD

**Issue by dhobbs** [carymrobbins/intellij-haskforce#195]
I'm using the IDEA 15 EAP with ghc-mod 5.4.0.0 and GHC 7.10.2

ghc-mod fails with the following error.

```
Unable to parse problems from ghc-modi: You must run ghc-mod in the project directory as returned by `ghc-mod root`. Currently in: "/Users/darren/figtree/.idea"but should be in "/Users/darren/figtree"
```

It might be possible to fix this from intellij itself but so far I haven't been able to find where it's selecting the .idea dir.

**Comment by carymrobbins** [comment]
Support for ghc-mod needs to be updated to support the latest versions.  See #182.  In this case, the module file must be located in the .idea dir for some reason.  Possibly the project was not created as a Haskell project?  When creating a project, the module file (.iml) should be created and placed in the same directory as the .cabal file.  Although, maybe IDEA 15 puts module files in the .idea dir now.

Either way, once ghc-mod 5.4 support is done this issue will get resolved as well.

**Comment by carymrobbins** [comment]
@dhobbs - Closing as ghc-mod 5.4 support is in the latest release.  Please reopen if you still encounter this issue.  I recommend removing any existing `*.iml` files in your project, as well as the `.idea` directory and freshly importing the project, choosing "stack" as your import model.
