### ISSUE TITLE
Error with initial '\' in String

### ISSUE THREAD

**Issue by orome** [carymrobbins/intellij-haskforce#196]
With

    decorate ch = ch:"\818\773"

or even just

    "\818\773"

I get an inspection error in the IDE

    HaskellTokenType." or HaskellTokenType.STRINGTOKEN expected, got '\'

but no build error, and no errors or warnings in GHCi or IHaskell.

Any idea what this is or how to get rid of it? I don't understand what it is saying.

**Comment by carymrobbins** [comment]
That's a bug in HaskForce's internal Haskell parser.  It should be a pretty simple fix, I'll include it in the next release.

**Comment by orome** [comment]
Thx. Fortunately not blocking (everything still builds).

**Comment by carymrobbins** [comment]
This should be resolved in the next release, **v0.3-beta.24**.
