### ISSUE TITLE
No spelling inspections

### ISSUE THREAD

**Issue by orome** [carymrobbins/intellij-haskforce#197]
I don't get any spelling inspections, even when I have this enabled in the IDE settings. In fact, I see no way to spellcheck at all!

**Comment by carymrobbins** [comment]
Seems that HaskForce needs to explicitly provide spellcheck support.  Looks pretty trivial, I should be able to have it available in the next release.

**Comment by orome** [comment]
Cool. Thx.

**Comment by carymrobbins** [comment]
Ok, this should be available in the next release, **v0.3-beta.23**.
