### ISSUE TITLE
Cabal install dependencies fails on OS X

### ISSUE THREAD

**Issue by psfblair** [carymrobbins/intellij-haskforce#200]
Using the self-contained Haskell for Mac OS X, trying to build my project (with "install cabal dependencies" set):

Information:cabal: Install dependencies
Information:cabal: '/Applications/Developer/ghc-7.10.2.app/Contents/lib/ghc-7.10.2/bin/ghc'
Information:cabal: ghc: missing -B<dir> option
Information:9/23/15, 12:49 PM - Compilation completed with 1 error and 0 warnings in 979ms
Error:cabal: install dependencies failed.

Ideas?

**Comment by carymrobbins** [comment]
That `ghc: missing -B` option usually suggests that you're pointing to an invalid ghc.

First, what paths do you have set in the Haskell Compiler settings?  If you'd like to debug this and you are on IRC, feel free to jump in the #haskforce channel on freenode and ping me.

**Comment by carymrobbins** [comment]
(This seems related to #184)

**Comment by psfblair** [comment]
Outcome of the discussion on IRC:

This issue is caused by not pointing to the right ``ghc``. The relocatable Haskell on OS X hard-links the ``ghc`` executable from ``ghc-7.10.2.app/Contents/bin/ghc`` to ``ghc-7.10.2.app/Contents/lib/ghc-7.10.2/bin`` -- but in the latter directory there is no ``cabal``. In the Haskell Compiler settings, the ``ghc`` executable path should be ``ghc-7.10.2.app/Contents/bin/ghc`` which is also the directory where ``cabal`` lives. Also, in the module settings, the Haskell SDK home directory should be ``ghc-7.10.2.app/Contents`` .
