### ISSUE TITLE
Build fails with "cabal configure failed" on OSX

### ISSUE THREAD

**Issue by psfblair** [carymrobbins/intellij-haskforce#201]
Using the relocatable Haskell for OSX, building without installing cabal dependencies, I get the following (whether or not I have "Build With Cabal" checked):

Information:cabal: Start configure
Information:9/23/15, 12:59 PM - Compilation completed with 1 error and 0 warnings in 2s 829ms
Error:cabal: configure failed.

I can't get any more information even if I add the "-v" flag to cabal. My ghc is in /Applications/Developer/ghc-7.10.2.app/Contents/lib/ghc-7.10.2/bin/ghc and my cabal in /Applications/Developer/ghc-7.10.2.app/Contents/bin

**Comment by carymrobbins** [comment]
This may be related to your other issue, #200.

**Comment by psfblair** [comment]
Yes. Solved by the solution to #200.
