### ISSUE TITLE
What does "enable tests" do

### ISSUE THREAD

**Issue by orome** [carymrobbins/intellij-haskforce#202]
What does "Make Project" do? Specifically what commands is it executing, with what flags and arguments?

It seems to be unnecessary in most cases. For example, if I `cabal test`, any changes to my source get recompiled anyway. 

Also, in that context, what does the compiler's "enable tests" option do? I have a test that fails with exit code 1, and have this option enabled, but I get no feedback that anything has failed.

**Comment by carymrobbins** [comment]
> What does "Make Project" do? Specifically what commands is it executing, with what flags and arguments?

Make Project will just build your project with cabal, using the flags provided in the settings.

> It seems to be unnecessary in most cases. For example, if I cabal test, any changes to my source get recompiled anyway.

Right, so it just depends on whatever your workflow is.  Many times you just want to build it without having to run your test suite.

> Also, in that context, what does the compiler's "enable tests" option do? I have a test that fails with exit code 1, and have this option enabled, but I get no feedback that anything has failed.

It basically passes `--enable-tests` to `cabal configure`.  This is so you can run test suites.  Note that if you run `cabal test` from the IDE this option is automatically enabled for you.

**Comment by orome** [comment]
Cool, thanks. I was a bit confused by how things interacted (e.g. why I could test, with the IDE, even of I'd unchecked "enable tests").

So to be clear: "Make Project" (as well as running testing from the IDE) will have side effects (it runs `cabal configure`?), in that having run it, any subsequent Cabal commands (e.g., from the command line or External Tools) will be subject to whatever IDE compiler options were in effect when I last ran "Make Project" (unless I also run `cabal configure` from the command line). Or — is `cabal configure` only run when I apply changes in the compiler config dialog?

**Comment by carymrobbins** [comment]
Sorry about the delayed response.

> "Make Project" (as well as running testing from the IDE) will have side effects (it runs cabal configure?), in that having run it, any subsequent Cabal commands (e.g., from the command line or External Tools) will be subject to whatever IDE compiler options were in effect when I last ran "Make Project" (unless I also run cabal configure from the command line).

Correct, there's not really a way to sandbox this and prevent side-effects (from what I can tell).  It seems most users are moving to stack anyway, so once I'm done with stack support this should mostly become a legacy issue.

**Comment by orome** [comment]
I guess I need to learn some Stack then! This is minor in any case (I'm more interested in #196, #198, #199 and #182).

**Comment by carymrobbins** [comment]
Closing this as I believe it has been addressed.  @orome - please reopen if I missed something.
