### ISSUE TITLE
Auto-completion does not work

### ISSUE THREAD

**Issue by orome** [carymrobbins/intellij-haskforce#203]
The ["Intelligent, context-aware autocompletion"](http://carymrobbins.github.io/intellij-haskforce/) illustrated as a feature doesn't work for me. I get a few basic completions, but no package, function, or keyword completion.

**Comment by carymrobbins** [comment]
Really, this is just the result of #182.  Once we support ghc-mod 5.4 this should work for you.  For others using an older version of ghc-mod this shouldn't be a problem.

**Comment by carymrobbins** [comment]
@orome - Closing this as ghc-mod 5.4 support is finally in.  Sorry for the delay!
