### ISSUE TITLE
Autocompletion (autosuggestions) not working when hiding something

### ISSUE THREAD

**Issue by AurimasAnskaitis** [carymrobbins/intellij-haskforce#209]
When using this code 
```haskell
module Main where

import Data.Vector

main :: IO ()
main = do
    let v = singl
    print 2
```
I get the suggestion for "singleton".

Using this code (added hiding (unsafeHead)) no suggestions are popped. 
```haskell
module Main where

import Data.Vector hiding (unsafeHead)

main :: IO ()
main = do
    let v = singl
    print 2
```

The behaviour is very consistent and happens every time.
Maybe this is a problem with ghc-mod (5.4 with legacy-interactice flag) which still has some problems with "package is hidden".

**Comment by carymrobbins** [comment]
This should be resolved in the next release, **v0.3-beta.25**.  Please re-open this issue if the problem persists.  Thanks for reporting!
