### ISSUE TITLE
Lexing error for infix operator :->

### ISSUE THREAD

**Issue by chrisosborn** [carymrobbins/intellij-haskforce#218]
I am getting a lexing error matching against the following pattern:

```
x PSQueue.:-> _
```

The squiggly red line is under the underscore character, and the error in the tooltip indicates that it is not an expected token.

I believe this line should be accepted by the lexer and parser, as GHCi accepts it.

**Comment by carymrobbins** [comment]
This should be resolved in the next release: **0.3-beta.35**

**Comment by chrisosborn** [comment]
Great!
