### ISSUE TITLE
External libraries point to old versions following GHC update

### ISSUE THREAD

**Issue by orome** [carymrobbins/intellij-haskforce#220]
After updating from GHC 7.10.2 to 7.10.3 (using Homebrew) the "External Libraries" are still listed as
```
/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2
```
How does one ensure that these get updated to match the current versions?

**Comment by carymrobbins** [comment]
@orome - I'm a little confused by this.  HaskForce doesn't manage your external libraries at all.  Where are you seeing this?

**Comment by orome** [comment]
<img width="1012" alt="screen shot 2015-12-14 at 2 17 29 pm" src="https://cloud.githubusercontent.com/assets/757327/11791099/7a7b207a-a26d-11e5-96b5-aa0c578d3c95.png">
<img width="666" alt="screen shot 2015-12-14 at 2 16 28 pm" src="https://cloud.githubusercontent.com/assets/757327/11791098/7a77efd6-a26d-11e5-9bde-9224d1869c55.png">

**Comment by carymrobbins** [comment]
Oh I see.  The SDK home path isn't used, so this shouldn't affect anything.  In the latest versions of HaskForce, you don't need to setup the SDK at all as it's inferred from your build tool.  

Maybe it'd be better to have the SDK path updated to point to your stack executable to make it less ambiguous.

**Comment by orome** [comment]
@carymrobbins — What should I do to fix it?

**Comment by carymrobbins** [comment]
I don't think it's affecting anything.  But if the path bothers you, you can just modify it to point where you'd like, e.g. the stack executable.  But once again, it shouldn't make a difference either way.

**Comment by orome** [comment]
@carymrobbins — In that SDK dialog?

**Comment by carymrobbins** [comment]
Exactly, where it says **Haskell SDK home path**.

**Comment by orome** [comment]
@carymrobbins — It won't let me. I'll just leave it. I don't understand what it is or why its there.

**Comment by orome** [comment]
After much experimenting, I found this and chose "Haskell", which seems to work:

<img width="515" alt="screen shot 2016-01-03 at 8 15 47 am" src="https://cloud.githubusercontent.com/assets/757327/12078912/4ae5b188-b1f2-11e5-9ed3-43e39a5f951e.png">

But this sets the path in the "Platform Settings" to and odd (and seemingly meaningless) value:

<img width="835" alt="screen shot 2016-01-03 at 8 17 24 am" src="https://cloud.githubusercontent.com/assets/757327/12078919/82d5835c-b1f2-11e5-8dc5-0e18a30e066c.png">

It all seems to work again now, but I'm not sure what's going on or whether I've got it things set right.

**Comment by carymrobbins** [comment]
Currently, the SDK path _is_ meaningless.  Certain things (e.g. building) seem to require having an SDK, so the plugin will create the SDK for you upon project creation or import.  The SDK merely existing appears to be the required prerequisite for certain functions.

In reality, the SDK isn't really used for anything, so it can mostly be ignored.

**Comment by orome** [comment]
That seems to be the case. I have other non-Java projects in the IDE (e.g. Mathematica) that for which I never use "build", and these don't seem to care that there's no SDK set at all. Building seems to need one, but if it's not actually used (as here), it can be anything (it seems).

**Comment by carymrobbins** [comment]
Exactly.  I'll go ahead and close this issue, but let me know if some issues arise and we can revisit this if need be.
