### ISSUE TITLE
ghc-modi tool: Allow custom flags other than legacy-interactive

### ISSUE THREAD

**Issue by adinapoli** [carymrobbins/intellij-haskforce#224]
Hey there!

Great job on this plugin, keep it up!

I wanted to give it a serious shot for work, but I'm having some problems with ghc-modi, but it's orthogonal to this issue. I want to force other flags in the ghc-modi section other than `legacy-interactive`, but this lines of code seems to completely wipe and replace the content with legacy-interactive only:

https://github.com/carymrobbins/intellij-haskforce/blob/05cac21377bdd9242dd3bd27f222ba5deea5bcb6/src/com/haskforce/settings/HaskellToolsConfigurable.java#L343

Do you think it would make sense to simply append `legacy-interactive` rather than overriding everything?

Thanks!

Alfredo

**Comment by carymrobbins** [comment]
@adinapoli - Nice catch.  That sounds like it should work just fine.  Would you like to put a PR together?  If so, I'll be happy to merge it.

**Comment by adinapoli** [comment]
@carymrobbins Hey man, thanks for the quick reply. I will try to cook up something off working hours then :wink:

**Comment by adinapoli** [comment]
@carymrobbins I have missed the hacking-window for tonight, as I spent most of it configuring the project :wink: 

This is where I've got so far (will polish and issue a PR tomorrow night).

https://github.com/carymrobbins/intellij-haskforce/compare/master...adinapoli:issue-224

An open question:

Is that normal that my patch also includes what seems spurious stuff in the .iml files?
