### ISSUE TITLE
ghc-mod + stack support

### ISSUE THREAD

**Issue by carymrobbins** [carymrobbins/intellij-haskforce#229]
It seems that ghc-mod and stack don't play very nice together.  For one, the PATH hacks that are done for ghc-mod so it can find your configured ghc don't work at all when using stack, since it manages your ghc.  A workaround is to configure ghc-mod and ghc-modi to work within `stack exec`.

![image](https://cloud.githubusercontent.com/assets/3103764/12500067/44dba8c4-c075-11e5-8c40-694d770c4ee1.png)

It would be better if HaskForce knew to do this for you.

**Comment by korayal** [comment]
I think it is possible when you add `--with-stack=<stack/binary/path>`  to flags. (or maybe add it off the shelf since HaskForce already knows the path of stack and if we are using stack or not)

**Comment by carymrobbins** [comment]
Good point!  No reason HaskForce shouldn't be able to do this on its own.

Nice work @korayal, this should be pretty straightforward to implement.

**Comment by carymrobbins** [comment]
This has been resolved in the latest release, **v0.3-beta.27**.
