### ISSUE TITLE
Stack imports unnecessary root module

### ISSUE THREAD

**Issue by carymrobbins** [carymrobbins/intellij-haskforce#230]
When importing a stack project which consists of a single package at `.`, the project importer creates two modules - one for the imported module, and another for the "root" project.  This is useful when we have packages as subdirectories, but not when we have a single package already at the root.

**Comment by carymrobbins** [comment]
This has been resolved in the latest release, **v0.3-beta.27**.

**Comment by develop7** [comment]
Confirming, it's fixed.
