### ISSUE TITLE
Add support for stack run similar to cabal run

### ISSUE THREAD

**Issue by AndreasPK** [carymrobbins/intellij-haskforce#238]
The plugin currently only supports cabal for the run/test configurations.

Adding similar support for stack would be a nice feature.

**Comment by carymrobbins** [comment]
This probably wouldn't be too difficult, we'd just need to inspect the cabal file for the executable name and then call it via `stack exec <name>`.  The implementations in `com.haskforce.run` could be followed to implement this.
