### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by JohnReedLOL** [carymrobbins/intellij-haskforce#239]
Can you help?

http://stackoverflow.com/questions/35259912/how-to-get-haskell-documentation-to-appear-in-intellij

**Comment by carymrobbins** [comment]
@JohnReedLOL - Thanks for pointing me to that SO question.  I've provided a comment hopefully providing some clarity around how to proceed.  As this appears to be mostly related to providing documentation for a library function, closing as this is duplicated by #187.
