### ISSUE TITLE
Extend selection (Cmd + w) does not select enclosing list

### ISSUE THREAD

**Issue by fokot** [carymrobbins/intellij-haskforce#246]
I'm 
`show ps = unlines $ map (\f -> f ps) [path, show.width, show.height, show.currentSlide]`
When the cursor is in the middle of width it select in this order:
`width`
`show.width`
`unlines $ map (\f -> f ps) [path, show.width, show.height, show.currentSlide]`
`= unlines $ map (\f -> f ps) [path, show.width, show.height, show.currentSlide]`
`show ps = unlines $ map (\f -> f ps) [path, show.width, show.height, show.currentSlide]`
I would expect selecting enclosing list first (that is what I wanted to do).

**Comment by tobiasgwaaler** [comment]
It seems like parenthesis and brackets are being confused for "the same thing", you can reproduce with a simpler case:
`foo = (\l -> id) [1,2]`
With the cursor inside the list, the same thing happens.

**Comment by tobiasgwaaler** [comment]
maybe the reason for this is that `listlike` in `haskell.bnf` is declared as `private`, meaning it won't create a node in the AST? https://github.com/carymrobbins/intellij-haskforce/blob/master/src/com/haskforce/Haskell.bnf#L445

**Comment by tobiasgwaaler** [comment]
removing `private` before `listlike` makes Extend selection behave as it should, but maybe there is a good reason why listlike was private in the first place?

**Comment by carymrobbins** [comment]
@tobiasgwaaler - Nice work!  The only thing is that it changes the resulting AST, so some existing logic may break as a result.  Feel free to push up your changes and see if the Travis build passes.  If it does, I'd be willing to merge it in as a pull request.

**Comment by tobiasgwaaler** [comment]
@carymrobbins thanks, will do!

**Comment by carymrobbins** [comment]
Thanks @tobiasgwaaler for your fix, I've merged it, so we'll see it in the next release **0.3-beta.30**
