### ISSUE TITLE
[Idea 16 EAP] Can't see `Stack` in external model list on Import Project window

### ISSUE THREAD

**Issue by korayal** [carymrobbins/intellij-haskforce#248]
When I try to import an active project, I don't see `Stack` as an option (even though it contains a file named `stack.yaml`)

IDEA Version (IU-145.184)
Haskforce (0.3-beta.29)

**Comment by carymrobbins** [comment]
@korayal - I think this is actually a problem with the `packages` key not being present.  Is that the case with your issue?

According to the [docs](http://docs.haskellstack.org/en/stable/yaml_configuration/), a missing `packages` key indicates to use the root directory as the package.  Currently HaskForce doesn't assume this, but it should.

**Comment by carymrobbins** [comment]
This should now be resolved in the latest release, **v0.3-beta.30**. Please reopen if you are still experiencing the issue.
