### ISSUE TITLE
Using stack marks import as error even the regarding package is specified in .cabal file

### ISSUE THREAD

**Issue by foofighter2146** [carymrobbins/intellij-haskforce#251]
I use haskforce together with stack. If I define an import, e.g. `import Data.Text`, before I define the regarding package text in the .cabal file in the library build-depends section, haskforce marks the import correctly as an error (hidden package). If I add the dependency in the .cabal file and call 'stack build' then stack resolves all dependencies, but the error message still remains in the IDE. If I add a further Haskell file and use in the new file`import Data.Text `too, everything works fine again in both Haskell modules.

**Comment by carymrobbins** [comment]
@foofighter2146 - This probably has to do with the ghc-modu process (`ghc-mod --interactive`) retaining it's original state.  You can currently get around this by restarting ghc-modi by going to **Tools > Restart ghc-modi**.

Maybe changes to a stack or cabal file should prompt and ask you if you'd like to restart the ghc-modi process for that module.

**Comment by foofighter2146** [comment]
@carymrobbins - Thank your the fast answer. Before I opened this issue, I had tried to restart ghc-modi and to invalidate caches of IDEA and restart the IDE. Both doesn't help to get rid of the error message.

But maybe you got the point: I wonder how I get the information that the restart of ghc-modi is successful. It was not printed into the Event Log. Do you know how I can check the status of restarting ghc-modi?

**Comment by carymrobbins** [comment]
Nothing fancy, but you can check the processes manually -

```
$ ps aux | grep ghc-mod
```

I'm actually working on building in a tool pane so you can actually see what's going on with ghc-mod to make debugging these sorts of issues easier.

**Comment by foofighter2146** [comment]
Strange stuff, this ghc-mod. Sometimes it seems that it stops magically even Intellij and HaskForce are alive and I had not used the restart link.

However, I found a small workaround that solves my problem: Adding dependency to cabal-file, call `stack build`, remove the dependency by commenting it out, call `stack build` again, remove comments and call `stack build` for a third time. At last ghc-mod got it and removes the error message.  Not very elegant, but it works.

**Comment by carymrobbins** [comment]
@foofighter2146 - That workaround sounds terrible.  Hopefully in the next day or so I should have the new release out.  With it we'll get the Haskell Tools Console (see #237) which will display commands sent to and output received from external tools.  This should make understanding and debugging issues like these much easier.

**Comment by carymrobbins** [comment]
The [Haskell Tools Console](https://github.com/carymrobbins/intellij-haskforce/wiki/Quick-Start-Guide#haskell-tools-console) is now available in the latest release, **v0.3-beta.30**.  If you install the latest release and are able to reproduce the issue, include a paste of the tools console for ghc-modi.  From there that should give some insight as to what is going wrong.

**Comment by foofighter2146** [comment]
I installed now the latest release, v0.3-beta.30. Of course, the problem still occurs. If I first specify the import and then add the regarding dependency, `ghc-modi` doesn't check the update. Compiling with `stack build` works fine again, but the error remains. Example:

1. Add `import Network.HTTP.Types`: `ghc-modi` marks the missing dependency correctly

**Comment by foofighter2146** [comment]
Again I have trouble with this issue today. First I understood that restarting ghc-modi not takes minutes, but the message of that it has done the restarting. After many tries I got the message 

`ghc-modi took too long to respond (waited 5000 milliseconds)`

At the end of try and error the wrong error message that reports a missing dependency gone away after I changed the order in the list of dependencies in the .cabal file.

I suppose this is a problem that regards to ghc-mod, and not to HaskForce.  Maybe we should close this issue here?

**Comment by carymrobbins** [comment]
If it is an upstream issue, I think we can leave it open until it gets resolved, that way it's easier for others to correlate it with problems they may have, plus it's probably better for it to stay on my radar.

Ghc-modi taking _minutes_ to start is certainly a problem.  Am I understanding correctly that this happens also when running the following from the command line?

```
/opt/stack/stack-1.0.4-linux-x86_64/stack exec -- /home/foofighter2146/.cabal/bin/ghc-mod legacy-interactive
```

A few questions that came to mind -

* What version of ghc-mod are you using?

* What does the directory structure look like for your project?

* What working directory are you using when executing that command?  (It should be the proper subproject dir where the cabal file lives).

@DanielG - Do you have any additional ideas?

**Comment by foofighter2146** [comment]
`ghc-mod --version` says `ghc-mod version 5.4.0.0 compiled by GHC 7.10.3`

Because currently I learn Haskell again (after about 20 years abstinence) I use the simple structure for the example code that I get by creating a new stack project with HaskForce inside Idea IntelliJ environment. That is a working directory with a the cabal file and a sub directory `src` with a few Haskell files. All stack commands I execute inside this working directory.

The line 

`Starting ghc-modi process: /opt/stack/stack-1.0.4-linux-x86_64/stack exec -- /home/foofighter2146/.cabal/bin/ghc-mod legacy-interactive`

is what the Haskell Tools Console says if I use the restart function of the IDE menu. Is the execution path of the restart ghc-modi function the same one as the path of the working directory?

**Comment by carymrobbins** [comment]
> ghc-mod --version says ghc-mod version 5.4.0.0 compiled by GHC 7.10.3

It's probably a good idea to use the latest version of ghc-mod, which is 5.5.0.0.  Once you are using the new the new version, update the configured path in HaskForce accordingly.  I'd also test on the command line as well to see how long it takes to execute commands.  Something like -

```
time /path/to/stack exec /path/to/ghc-mod check path/to/file.hs
```

Try it also with `ghc-mod legacy-interactive` and see if the performance is the same.

> Is the execution path of the restart ghc-modi function the same one as the path of the working directory?

The working directory should be the directory that contains your cabal file.  I can update the Haskell Tools Console to display the working directory as well in these cases so it's clearer.

-------------------

On a side note, I've been looking into using vanilla ghc and/or ghci (ghc --interactive) for doing some of this sort of error checking in place of delegating it to ghc-mod.  It seems like a better solution for users to avoid the overhead of configuring ghc-mod.

**Comment by foofighter2146** [comment]
Very cool - updating to ghc-mod 5.5.0.0 was the solution! @carymrobbins Thank you very much for your patience to find the answer. And the update of the Haskell Tools Console works well, too.
