### ISSUE TITLE
Should prevent creation of a stack project with whitespace in name

### ISSUE THREAD

**Issue by huyz** [carymrobbins/intellij-haskforce#252]
I created a project with a space in the name.  I selected "Build with stack".
When the project was created, no stack.yaml file was generated.

**Comment by tobiasgwaaler** [comment]
One suggestion is to allow spaces in the project name, but replace them with dashes when creating the cabal file, like so:
https://github.com/carymrobbins/intellij-haskforce/compare/master...tobiasgwaaler:error-messages-creating-invalid-stack-project?expand=1

**Comment by tobiasgwaaler** [comment]
It would perhaps be better to replace spaces with dashes while you're typing in the project name, to make it more visible what the actual project name/cabal name will be

**Comment by carymrobbins** [comment]
Maybe we could just have the field validated and ensure there are no spaces, letting the user decide what to do.  Having Swing text fields update as you type always seems problematic to me.

**Comment by tobiasgwaaler** [comment]
Good idea, I'll try to implementing it :) Hopefully it's as simple as overriding `validate()` in [`HaskellModifiedSettingsStep `](https://github.com/carymrobbins/intellij-haskforce/blob/master/src/com/haskforce/HaskellModuleBuilder.scala#L351)
