### ISSUE TITLE
New project : no stack,yaml

### ISSUE THREAD

**Issue by rwobben** [carymrobbins/intellij-haskforce#257]
Hello, 

When I made a new project with new project and then choose for Stack
A new project is made. 
But when you want to build is , I see a error message that stack,yaml cannot be found.

Another difference.
If you make a new project with the prompt, you will have a directory app with main,hs in it and a directort src with lib,hs in it.

**Comment by tobiasgwaaler** [comment]
Could it be that the Project Name you typed in had a white space character in it? That's a known issue we've fixed (but it's not released yet) 
https://github.com/carymrobbins/intellij-haskforce/issues/252

**Comment by rwobben** [comment]
yep, I named the project haskell book instead of HaskellBook

**Comment by tobiasgwaaler** [comment]
Ok, good :) So this issue can be closed?

**Comment by rwobben** [comment]
yep, I  tested it with a name without spaces and a .yaml file is being made. 
so I close this issue.
