### ISSUE TITLE
External annotators (ghc-mod) should not halt the IDE

### ISSUE THREAD

**Issue by carymrobbins** [carymrobbins/intellij-haskforce#259]
Currently, we use a timeout to give ghc-mod enough time to respond to requests made for annotating errors in the source.  However, sometimes this gets called many times and can really negatively impact user experience due to the halting of the IDE (e.g. #258).

Why not just annotate the source once we get a response?  Well, the source may have changed since then!  My current idea is we could calculate a checksum from the source text and submit that along with the ghc-mod request; then, the response would give that checksum back.  If our current source checksum matches the response's, we should be good to annotate the source without needing to halt the IDE.

**Comment by carymrobbins** [comment]
Ok, it seems that the real problem here is that the call to [HaskellCompletionContributor.loadCacheData in the HaskellExternalAnnotator](https://github.com/carymrobbins/intellij-haskforce/blob/master/src/com/haskforce/highlighting/annotation/external/HaskellExternalAnnotator.scala#L45) is blocking.  This seems obvious now, and really this belongs somewhere else.

I'm experimenting with implementing a ProjectComponent that will take care of this task in the background and be a better place for it to live.

**Comment by tobiasgwaaler** [comment]
Nice work! So that means we don't need keeping track of checksums etc.?

**Comment by carymrobbins** [comment]
Exactly, so far it seems to work really well.

**Comment by carymrobbins** [comment]
Closing as this has been fixed since **0.3-beta.31**.
