### ISSUE TITLE
Limited syntax highlighting on v0.3-beta.30

### ISSUE THREAD

**Issue by lovromazgon** [carymrobbins/intellij-haskforce#262]
After upgrading to `v0.3-beta.30` I lost almost all syntax highlighting, except infix operators (e.g. `+`, `-`, `++`, `==` ...) and string literals. Everything else was not highlighted at all (nothing orange, yellow or violet). The problem disappeared after reverting back to `v0.3-beta.29`.

I'm running IntelliJ IDEA 14.1.6, build 141.3056 on Ubuntu 15.10.

**Comment by carymrobbins** [comment]
Nothing changed with the syntax highlighter, but I believe I built that release against a newer version of IntelliJ, build `IU-143.2287.1` (relative to the the previous release which I believe would have been built against `IU-143.381.42`.  Both of these versions are IntelliJ 15, so maybe there was some regression in IntelliJ's lexer API.

Syntax highlighting seems to work for me in IntelliJ 15 and 16.  I'll download IntelliJ 14 and see if I can reproduce your issue there.
