### ISSUE TITLE
RecursiveDo

### ISSUE THREAD

**Issue by mcastse** [carymrobbins/intellij-haskforce#264]
Recursive do seems to work when mdo, now deprecated, is used. However, using do rec syntax I find an error is always, incorrectly, indicated at the first appearance of <-.

**Comment by carymrobbins** [comment]
@mcastse - Could you paste a small example to make sure I address your specific use case?

**Comment by mcastse** [comment]
"Small" is tricky since I discovered the issue when using examples which come with the Earley [sic] library from Hackage. I don't really have much use for recursive do expressions otherwise. All of the examples that come with the library use mdo; for example, English.hs:

{-# LANGUAGE RecursiveDo #-}

import Control.Applicative

import Text.Earley

import qualified Data.HashSet as HS

 

type Noun      = String

type Verb      = String

type Adjective = String

 

nouns, verbs, adjectives :: HS.HashSet String

nouns      = HS.fromList ["parsers", "sentences", "grammars"]

verbs      = HS.fromList ["parse", "munch", "annihilate", "confuse", "use"]

adjectives = HS.fromList ["many", "great", "long", "confusing"]

 

 

data Sentence = Sentence NounPhrase VerbPhrase

  deriving Show

data NounPhrase = NounPhrase Adjective NounPhrase

                | Noun Noun

  deriving Show

data VerbPhrase = VerbPhrase Verb NounPhrase

                | Verb Verb

  deriving Show

 

sentence :: Grammar r (Prod r String String Sentence)

sentence = mdo

  noun       <- rule $ satisfy (`HS.member` nouns)      <?> "noun"

  verb       <- rule $ satisfy (`HS.member` verbs)      <?> "verb"

  adjective  <- rule $ satisfy (`HS.member` adjectives) <?> "adjective"

  nounPhrase <- rule $  NounPhrase <$> adjective <*> nounPhrase

                    <|> Noun <$> noun

                    <?> "noun phrase"

  verbPhrase <- rule $  VerbPhrase <$> verb <*> nounPhrase

                    <|> Verb <$> verb

                    <?> "verb phrase"

  return $ Sentence <$> nounPhrase <*> verbPhrase <?> "sentence"

 

main :: IO ()

main = do

  let p = fullParses (parser sentence) . words

  print $ p "parsers use grammars"

  print $ p "parsers munch long sentences"

  print $ p "many great sentences confuse parsers"

  print $ p "parsers use use"

  print $ p "grammars many great confusing

 

I understand that mdo syntax is deprecated. So I changed things to:

 

{-# LANGUAGE ScopedTypeVariables, RecursiveDo #-}

module Main (main) where

 

import           Control.Applicative ((<|>))

import           Data.HashSet        (HashSet, fromList, member)

import           Text.Earley         (Grammar, Prod, Report, fullParses, parser,

                                      rule, satisfy, (<?>))

 

{-

From the documentation:

 

data Prod r e t a where

 

A production.

 

The type parameters are:

 

a: The return type of the production.

 

t for terminal: The type of the terminals that the production operates on.

 

e for expected: The type of names, used for example to report expected tokens.

 

r for rule: The type of a non-terminal.

This plays a role similar to the s in the type ST s a.

Since the parser function expects the r to be universally quantified,

there is not much to do with this parameter other than leaving it universally quantified.

-}

 

type Determiner  = String

type Noun        = String

type Verb        = String

type Preposition = String

type Adjective   = String

 

{-

S -> NP VP

NP -> Noun | Det Noun | Adj Noun | NP PP

VP -> Verb | Verb NP | VP PP

PP -> Prep NP

Det -> a

Noun -> banana | flies | fruit | time

Verb -> flies | like

Prep -> like

Adj -> fruit

-}

 

determiners, nouns, verbs, prepositions, adjectives :: HashSet String

determiners  = fromList ["a", "an"]

nouns        = fromList ["banana", "flies", "fruit", "time", "arrow"]

verbs        = fromList ["flies", "like"]

prepositions = fromList ["like"]

adjectives   = fromList ["fruit"]

 

 

data Sentence = Sentence NounPhrase VerbPhrase

  deriving Show

 

data NounPhrase = A_NP Adjective NounPhrase

                | N Noun

                | D_N Determiner Noun

                | A_N Adjective Noun

  deriving Show

 

data VerbPhrase = V_NP Verb NounPhrase

                | VP_PP VerbPhrase PrepPhrase

                | V Verb

  deriving Show

 

data PrepPhrase = P_NP Preposition NounPhrase

  deriving Show

 

isDeterminer, isNoun, isVerb, isPreposition, isAdjective  :: String -> Bool

isDeterminer = (`member` determiners)

isNoun = (`member` nouns)

isVerb = (`member` verbs)

isPreposition = (`member` prepositions)

isAdjective = (`member` adjectives)

 

determiner, noun, verb, preposition, adjective :: Prod r String String String

determiner  = satisfy isDeterminer  <?> "determiner"

 

noun        = satisfy isNoun        <?> "noun"

 

verb        = satisfy isVerb        <?> "verb"

 

preposition = satisfy isPreposition <?> "preposition"

 

adjective   = satisfy isAdjective   <?> "adjective"

 

grammar :: forall r . Grammar r (Prod r String String Sentence)

grammar = do

  rec

    nounPhrase <- rule $  A_NP <$> adjective  <*> nounPhrase

                      <|> N    <$> noun

                      <|> D_N  <$> determiner <*> noun

                      <|> A_N  <$> adjective  <*> noun

                      <?> "noun phrase"

  let prepPhrase :: Prod r String String PrepPhrase

      prepPhrase = P_NP <$> preposition   <*> nounPhrase <?> "prepositional phrase"

  rec

    verbPhrase <- rule $  V_NP  <$> verb       <*> nounPhrase

                      <|> VP_PP <$> verbPhrase <*> prepPhrase

                      <|> V     <$> verb

                      <?> "verb phrase"

  -- return $ Sentence <$> nounPhrase <*> verbPhrase <?> "sentence"

  rule $ Sentence <$> nounPhrase <*> verbPhrase <?> "sentence"

 

main :: IO ()

main = do

  print $ p "time flies like an arrow"

  print $ p "fruit flies like a banana"

  where

    p :: String -> [Sentence]

    p = fst . fullParses (parser grammar) . words

 

-- This ignores the report which has type Report String [String]

 

In Intellij Idea, using HaskForce, an error is indicated at the <- in the line

    nounPhrase <- rule $  A_NP <$> adjective  <*> nounPhrase

 

This effectively stops code analysis or hlint from showing anything useful. However, the code is correct and I can compile it (using the IDE) and run the program to get the expected results.

 

I expect similar behaviour from all uses of rec do syntax.

**Comment by mcastse** [comment]
Using the first example from https://wiki.haskell.org/MonadFix#Examples, try the following.

An error is indicated at the <- in    rec p <- newIORef (Node 0 p)

but both versions compile, run and display

 

node created

0

0

 

{-# LANGUAGE RecursiveDo #-}
module Main where

import Data.IORef
data Node = Node Int (IORef Node)

{-
mknode = mdo
  p <- newIORef (Node 0 p)
  putStrLn "node created"
  return p
-}

mknode = do
    rec p <- newIORef (Node 0 p)
    putStrLn "node created"
    return p

main = do
  p <- mknode
  Node x q <- readIORef p
  print x
  Node y _ <- readIORef q
  print y

**Comment by carymrobbins** [comment]
This should be resolved in the next release: **0.3-beta.35**

**Comment by mcastse** [comment]
Thank you. That seems to have done the trick :)
