### ISSUE TITLE
Parse error with ppragma

### ISSUE THREAD

**Issue by zjhmale** [carymrobbins/intellij-haskforce#267]
![image](https://cloud.githubusercontent.com/assets/6234553/14585729/a386dca6-04b1-11e6-8ae4-ed3e9bd860f0.png)

maybe the component after `ppragma*` [here](https://github.com/carymrobbins/intellij-haskforce/blob/master/src/com/haskforce/Haskell.bnf#L212) should be optional?

**Comment by carymrobbins** [comment]
Would a Haskell source only consisting of pragmas be considered valid?

**Comment by zjhmale** [comment]
as far as i known, if you use `HSpec` in a cabal or stack project, the spec file should only contains the specific pragmas. e.g. https://github.com/hspec/hspec-example/blob/master/test/Spec.hs
>Would a Haskell source only consisting of pragmas be considered valid?

**Comment by carymrobbins** [comment]
Well, I guess it should be optional then.

**Comment by carymrobbins** [comment]
This should be resolved in the next release: **0.3-beta.35**
