### ISSUE TITLE
Can't add Haskell SDK

### ISSUE THREAD

**Issue by androidfred** [carymrobbins/intellij-haskforce#273]
STEPS TO REPRODUCE
On a system that doesn't have Haskell installed, download Stack, put it in ~/.local/bin and add ~/.local/bin to PATH

Run 

`stack install hlint stylish-haskell ghc-mod` (they will be installed in ~/.local/bin)

In some appropriate folder (eg /home/user/src) run

```
stack new my-project
cd my-project
stack setup *NOTE*
stack build
stack exec my-project-exe
```

This should all work and output fine. 

*NOTE* Stack setup should trigger download of ghc, in my case to

```
./home/fred-fri/.stack/programs/x86_64-linux/ghc-7.10.3/lib/ghc-7.10.3/bin/ghc
./home/fred-fri/.stack/programs/x86_64-linux/ghc-7.10.3/share/doc/ghc
./home/fred-fri/.stack/programs/x86_64-linux/ghc-7.10.3/bin/ghc
```

On a system that doesn't have Intellij or any plugins installed (including no ~/.IntelliJIdea2016.1 folder), download and install the latest version, and follow the instructions for installing HaskForce (https://github.com/carymrobbins/intellij-haskforce/wiki/Quick-Start-Guide) and creating or importing a Stack project. (this works for me)

EXPECTED RESULT
Should be able to use plugin features

ACTUAL RESULT
None of the plugin features work. And when trying to add Haskell SDK under Project Structure, pointing to any of

```
./home/fred-fri/.stack/programs/x86_64-linux/ghc-7.10.3/lib/ghc-7.10.3/bin/ghc
./home/fred-fri/.stack/programs/x86_64-linux/ghc-7.10.3/share/doc/ghc
./home/fred-fri/.stack/programs/x86_64-linux/ghc-7.10.3/bin/ghc
```

results in an error 
```
"Probably SDK installed in './home/fred-fri/.stack/programs/x86_64-linux/ghc-7.10.3/bin/ghc' is corrupt"
```

**Comment by androidfred** [comment]
OK, after further investigation I've realized

-------------

"The SDK home path isn't used". (https://github.com/carymrobbins/intellij-haskforce/issues/220) It would be nice if there was a note about this in the Quick Start Guide because it's confusing.

-------------

Creating a lib folder, downloading external sources using `stack list-dependencies` and `stack unpack`, and marking them as Sources under Project Structure is required in order to be able to jump to their definitions. (https://github.com/carymrobbins/intellij-haskforce/issues/192) 

It would be nice if there was a note about this in the Quick Start Guide because it's confusing, and even nicer if HaskForce could do it for the user. 

A competing plugin does it (see https://github.com/rikvdkleij/intellij-haskell/search?utf8=%E2%9C%93&q=AddDependencies) by running `stack unpack` on every line output from running `stack list-dependencies`. (running this in command line does the same  `$ while read -r line; do stack unpack "${line// /-}"; done < <(stack list-dependencies)`)

Actually, even after doing this, while I can jump to sources of functions in external packages, I still can't jump to sources of things like `Maybe`, `IO` etc.

**Comment by carymrobbins** [comment]
Hopefully this wiki entry should suffice - https://github.com/carymrobbins/intellij-haskforce/wiki/Quick-Start-Guide#haskell-sdk

Regarding the adding dependency sources feature, I am always open to reviewing and accepting pull requests.  See the [CONTRIBUTING](https://github.com/carymrobbins/intellij-haskforce/blob/master/CONTRIBUTING.md#submitting-pull-requests) doc for more info.

I'll go ahead and close this issue; please reopen if you have any unaddressed concerns.
