### ISSUE TITLE
Hindent Support

### ISSUE THREAD

**Issue by jmmk** [carymrobbins/intellij-haskforce#274]
[Stylish Haskell](https://github.com/jaspervdj/stylish-haskell) isn't very prescriptive on the formatting of source code. It might be nice to have the option of using a more complete formatter like [hindent](https://github.com/chrisdone/hindent).

Would this be something that could be included in the plugin?

**Comment by carymrobbins** [comment]
I'd certainly accept a pull request if someone wants to add the feature.

For reference, [here's how Stylish Haskell support is currently implemented](https://github.com/carymrobbins/intellij-haskforce/blob/1de0873c46a4c669d3cc3f828c72ce3aa0a25dd0/src/com/haskforce/actions/HaskellStylishFormatAction.java).

**Comment by carymrobbins** [comment]
This has been implemented as part of PR #275 courtesy of @jmmk.  Thanks for your contribution!  This feature is in master and will be available in the next release, v0.3-beta.32.

**Comment by jmmk** [comment]
@carymrobbins there's a few pages in the wiki that need to be changes. Should I go ahead and make the changes or wait until the new release?

**Comment by carymrobbins** [comment]
If you want to update the wiki I'm fine with it.  I can go ahead and cut a new release with the feature over the weekend.

**Comment by jmmk** [comment]
Added hindent to https://github.com/carymrobbins/intellij-haskforce/wiki/Keyboard-Shortcuts and https://github.com/carymrobbins/intellij-haskforce/wiki/Quick-Start-Guide

**Comment by carymrobbins** [comment]
Nice work @jmmk!
