### ISSUE TITLE
including sources of external dependencies in jump to declaration

### ISSUE THREAD

**Issue by azadbolour** [carymrobbins/intellij-haskforce#277]
Hi,

What is the recommended way of adding the sources of external dependencies, so jumping to the declaration of an external dependency would bring up its source?

Many thanks.

Azad

**Comment by carymrobbins** [comment]
I currently have an open issue for this, so you may wish to follow it - https://github.com/carymrobbins/intellij-haskforce/issues/192

My general workflow is to create a `lib` dir and use `stack unpack` (or `cabal get` if you are not using stack) to obtain library sources for whichever libraries you wish to be able to jump to source.

Note that there are some issues with the current Haskell parser (both performance and correctness), so I wouldn't just unpack all your libraries immediately.  For more info, see issue https://github.com/carymrobbins/intellij-haskforce/issues/233
