### ISSUE TITLE
Stack-only Haskell installation gives various errors

### ISSUE THREAD

**Issue by OmanF** [carymrobbins/intellij-haskforce#280]
Hi.
First off, the technical details: Stack-based Haskell installation (i.e. installed Stack, then "stack setup" to install GHC **_globally_** as well as all stack modules that are installed globally).
Stack version 1.1.2 (with default, latest resolver).
GHC installed by stack is 7.10.3; GHC-mod is at 5.5.0.0 (as can be seen in the screenshots).
Machine is Xubuntu 16.04 (virtualized).

**_The issue_**: When importing a Haskell project created with "stack new" an error (shown on a screenshot attached) is displayed about GHC not being able to run because the file is missing... which is correct, but never have I configured it to look for GHC where the error message points.

After clicking the "Configure" button (settings shown in a screenshot attached) and confirming them, using the "Auto-find" tool to locate the various modules, another error pops-up (screenshot attached), regarding stack itself, saying error 13, permissions denied.
In the screenshot we can see everything stack-related on my machine has permissions 775 which should allow all to run those executables.

Also, trying to **create** a new stack-based Haskell project via the "New Project" button on IntelliJ (and choosing Stack as the build tool for the project) gives an error 13, permissions denied when trying to initialize the project (screenshot attached).

Also of note is that importing the file, in this case Lib.hs, to various other text-editors (emacs, Atom and Sublime Text) causes no issues with neither and I can do a "Show type" in all of these editors and get a result, so the issue is local to IntelliJ (with HaskForce) only.

**_Edit_**: All the editors/IDEs I use are run from the console meaning they have access to my $PATH.

(Please let me know what other info is required, if any).

Thanks!

![01_ghc_error_on_project_start](https://cloud.githubusercontent.com/assets/7848797/15882320/39e6d7fc-2d46-11e6-8f0d-b8cace57b656.png)
![02_haskell_settings_1](https://cloud.githubusercontent.com/assets/7848797/15882322/3c2555de-2d46-11e6-897f-1f699883bf1e.png)
![03_haskell_settings_2](https://cloud.githubusercontent.com/assets/7848797/15882325/40eaf6c8-2d46-11e6-84d1-1f7e428321c6.png)
![04_new_errors_after_confirming_settings](https://cloud.githubusercontent.com/assets/7848797/15882328/4412cc68-2d46-11e6-893f-5a0099c2d72b.png)
![05_dot_local_folder_has_permissions_775](https://cloud.githubusercontent.com/assets/7848797/15882331/475b6db2-2d46-11e6-9336-aa5ba85b9e20.png)
![06_stack_folder_and_soft_link_and_executable_have_permissions_775](https://cloud.githubusercontent.com/assets/7848797/15882332/4970c5ac-2d46-11e6-8854-3e9edc6d95b8.png)
![07_creating_new_haskell_project_gives_this_error](https://cloud.githubusercontent.com/assets/7848797/15882335/4cb217d4-2d46-11e6-8807-d4a98dbcb16a.png)

**Comment by carymrobbins** [comment]
It looks like the main issue here is that you have the `stack` executable configured as -

**/home/ohadf/Development/bin/stack**

Whereas, from your screenshots, it appears to be located at -

**/home/ohadf/Development/bin/stack-1.1.2/stack**

You can either configure HaskForce to use this executable or consider creating a symlink -

```
$ cd /home/ohadf/Development/bin
$ ln -s stack-1.1.2/stack
```

Regarding your ghc and cabal paths, my guess would be that they are set in the default project settings -

**File > Other Settings > Default Settings**

I'd go there to clear them out so new projects won't get these defaults.

**Comment by carymrobbins** [comment]
Also, it looks like you have your stack yaml file configured as -

**/home/ohadf/.stack/global-project/stack.yaml**

However, you probably want to use the _project's_ stack yaml, not the global one -

**/home/ohadf/Development/Projects/Haskell/TrialProject/stack.yaml**

**Comment by OmanF** [comment]
I think I should point my problem, sole problem, is not being able to get an expression's type by *alt-equals*-ing it. The key binding works but the pop-up says the type info can't be found.

To that, after changing my settings as per you comment (I already have a symlink pointing at the stack executable, or so my shell says when I ran the command) and pointing the stack variable to the **explicit** stack executable and clearing out the ghc and cabal paths on the default settings compiler build menu I still receive an error about ghc when importing and opening a file on a newly created stack-based project and still, no type info can be found.
(Name is the same but I assure you I *rm -rf*ed the previous project by that name and created a new one from scratch. Also, same behavior happens on a *completely* new project).

![screenshot_2016-06-08_18-12-44](https://cloud.githubusercontent.com/assets/7848797/15899818/aba35852-2da5-11e6-84d1-d4d6aab3337a.png)
![screenshot_2016-06-08_18-13-19](https://cloud.githubusercontent.com/assets/7848797/15899822/b026cca6-2da5-11e6-9172-2422645ee8e5.png)

**Comment by carymrobbins** [comment]
It looks like your stack path is still wrong, you have -

**/home/ohadf/Development/bin/stack-1.1.2**

Which points to a _directory_; instead, you'll need to point it to the executable -

**/home/ohadf/Development/bin/stack-1.1.2/stack**

**Comment by OmanF** [comment]
**Yes!**
Thank you very much.

This is my second issue I open on my own fumbling with configuration and I really appreciate the time and patience for hand-holding me until it works.

Thanks again!

**Comment by carymrobbins** [comment]
No problem at all!  I think this does exemplify an opportunity to improve the configuration experience (e.g. if the file is not executable, don't let you set it in the first place).

Feel free to post issues as you come across them or hop on our [gitter chat](https://gitter.im/carymrobbins/intellij-haskforce).
