### ISSUE TITLE
Building stack project remains stale

### ISSUE THREAD

**Issue by carymrobbins** [carymrobbins/intellij-haskforce#282]
When creating a project via `stack new` then importing it into HaskForce, the first build seems to work properly; however, successive builds don't seem to actually rebuild.

http://stackoverflow.com/questions/37754956/how-do-i-set-up-intellij-to-build-haskell-projects-with-stack

**Comment by wpm** [comment]
Started with a brand new "Hello Haskell" project: `stack new hellohaskell new-template -p "category:Example"`.

Did IntelliJ Import Project->[_choose the directory_]->Stack.

The SDK and stack.yaml files are properly identified. The `app`,  `src`, and `test` directories are properly marked as source and test roots. However, Make Project just copies source files to production and test subdirectories of out, though. Doesn't appear to compile anything. Likewise, when I try to add a Haskell Stack Run run configuration, there's no executable to specify.

I not actually seeing the first build work properly. However, if you do you `stack build` to build an executable from the command line, you can see how subsequent attempts to build from within IntelliJ would have no effect.

**Comment by wpm** [comment]
Build project doesn't compile anything, but does copy source beneath the `production` and `test` subdirectories of the Project compiler output. (Default `out`.) This looks wrong. It should be using the `.stack-work` output directory created by Stack.

Haskforce is not unaware of the `.stack-work` directory. If you build the program from the command line with `stack build`, and then create a Haskell Stack Run configuration with the Executable `hellohaskell-exe`. It correctly runs it.

Haskforce knows where Stack build products should go, it just doesn't put them there as part of the make process.

(I'm not sure if this is relevant, but the Project Settings Artifacts tab is empty.)

**Comment by carymrobbins** [comment]
Ok, it seems this commit https://github.com/carymrobbins/intellij-haskforce/commit/f793fec0741191e34905da8e306f41785b0522c1 introduced the bug.  The [HaskForceBuilder](https://github.com/carymrobbins/intellij-haskforce/blob/1494f083c7b8abecfebfc1c9fe1bc7b88cc62d3e/jps-plugin/src/com/haskforce/jps/HaskForceBuilder.java) class appears to not be visible to the external builder process as a result of dynamically generating the classpath.

I've introduced commit d9b8923d1544b9e5380f887e1da378e5d21ded5c which reverts the bad commit and resolves the issue.
