### ISSUE TITLE
Haskell Tools passes invalid --version argument to stylish-haskell

### ISSUE THREAD

**Issue by wpm** [carymrobbins/intellij-haskforce#283]
Under Haskell Tools in Preferences I have the path set to `stylish-haskell`. (I found this path using Auto Find.)

Periodically, IntelliJ gives me the following error:

    Haskell Tools
               Nonzero exit status (1) from command: /Users/williammcneill/Library/Haskell/bin/stylish-haskell --version
               Process stderr: Invalid option `--version'
               Usage: stylish-haskell [FILENAME]

The `--version` command line option is not supported by my version of `stylish-haskell`. I see the same error if I run `stylish-haskell --version` on the command line. (I don't see a "version" command line option, though `stylish-haskell --help` prints the version.

I used `cabal` to install `stylish-haskell`.

_ghc 7.10.3, stylish-haskell v0.5.17.0, cabal  1.22.5.0, stack 1.1.2, HaskForce 0.3-beta.33, IntelliJ IDEA Ultimate 2016.1.3, OS X 10.11.5_

**Comment by trevorwhitney** [comment]
I'm seeing this same issue, using `stylish-haskell v0.5.17.0` installed via stack

**Comment by sideeffffect** [comment]
this should fix it: https://github.com/jaspervdj/stylish-haskell/pull/113

**Comment by sideeffffect** [comment]
merged

**Comment by carymrobbins** [comment]
Special thanks to @sideeffffect for fixing this in stylish-haskell. I'm going to go ahead and close this. If instead you'd rather see HaskForce workaround this, feel free to re-open.
