### ISSUE TITLE
Extra comma in import lists

### ISSUE THREAD

**Issue by tolysz** [carymrobbins/intellij-haskforce#284]
According to: https://ghc.haskell.org/trac/ghc/ticket/870 one can put an additional comma when they specify which names they want to pull form a module

```
import A(a,b,)
```

**Comment by carymrobbins** [comment]
This should be resolved in the next release, **0.3-beta.36**

**Comment by tolysz** [comment]
Nice, as always a quick response :) Good Job!

**Comment by carymrobbins** [comment]
Thanks @tolysz!
