### ISSUE TITLE
Hlint returns "Unknown flag: --no-exit-code"

### ISSUE THREAD

**Issue by declension** [carymrobbins/intellij-haskforce#286]
Whilst I see #244, on a newly reconfigured Stack environment with latest Haskforce and IDEA 2016.1.3, I'm constantly getting

```
hlint
Nonzero exit status (1) from command: /home/nick/.local/bin/hlint --no-exit-code --version
Process stderr: Unknown flag: --no-exit-code
```

**Comment by shmish111** [comment]
Me too and it also happens with stylish-haskell:

```
Nonzero exit status (1) from command: /Users/davidsmith/.local/bin/stylish-haskell --version Process stderr: Invalid option `--version'  Usage: stylish-haskell [FILENAME]
```

**Comment by carymrobbins** [comment]
@shmish111 - That issue has been resolved in stylish-haskell, see: https://github.com/carymrobbins/intellij-haskforce/issues/283

@declension - What version of hlint are you running? It seems to work for me -

```
% hlint --no-exit-code --version
HLint v1.9.26, (C) Neil Mitchell 2006-2016

% echo $?
0
```

**Comment by declension** [comment]
$ hlint --version ; hlint --no-exit-code
    HLint v1.9.21, (C) Neil Mitchell 2006-2015
    Unknown flag: --no-exit-code

**Comment by carymrobbins** [comment]
Thanks @declension, maybe try upgrading to at least v1.9.26

**Comment by declension** [comment]
Thanks @carymrobbins

**Comment by carymrobbins** [comment]
No problem! I'll close this ticket, but feel free to reopen if you run into issues.
