### ISSUE TITLE
Raw HTML tags appear in tools console when ghc-modi errors

### ISSUE THREAD

**Issue by declension** [carymrobbins/intellij-haskforce#287]
If ghc-modi process fails for some reason (see #285), the error message in the Tools Console seems to be erroneously output (or over-escaped) in HTML:

```Killing ghc-modi due to process failure.<br/><br/>You can restart it using <b>Tools &gt; Restart ghc-modi</b><br/><br/>Executing ghc-modi command...```

Ubuntu `16.04`, Idea `2016.1.3`, Haskforce `v0.3-beta.35`

**Comment by carymrobbins** [comment]
This should be resolved in the next release, **0.3-beta.36**

**Comment by declension** [comment]
Thanks @carymrobbins !

**Comment by carymrobbins** [comment]
No problem, thanks for the report!
