### ISSUE TITLE
Unable to build Haskforce

### ISSUE THREAD

**Issue by LeanderK** [carymrobbins/intellij-haskforce#292]
the problem is in com.haskforce.ui.SListCellRendererWrapper

```scala
Error:(8, 7) class SListCellRendererWrapper needs to be abstract, since method getListCellRendererComponent in trait ListCellRenderer of type (x$1: javax.swing.JList[_ <: A], x$2: A, x$3: Int, x$4: Boolean, x$5: Boolean)java.awt.Component is not defined
class SListCellRendererWrapper[A](showItem: A => String) extends ListCellRenderer[A]
```
my scala is a bit rusty and i might have done something wrong, but i have not changed code yet so this is a bit surprising.

**Comment by carymrobbins** [comment]
How are you building? I assume you are using Java 8? What if you use `ant build.modules` from the command line instead?

**Comment by LeanderK** [comment]
yeah, java 8. It happens when i want to debug the plugin.

**Comment by carymrobbins** [comment]
@LeanderK - Sorry it took me so long to get back on this. I just pushed a change to master which should get around this problem. Let me know if this works for you.

**Comment by LeanderK** [comment]
I am currently not doing much beside sleeping and learning, i also think i am going slightly crazy from it ;) I may find time to test whether i can build it, but it may take some time before i can really start working on it.

**Comment by carymrobbins** [comment]
No problem at all! I've been pretty wrapped up with stuff as well and haven't had much time to work on HaskForce either.  Good luck on your exams!

**Comment by carymrobbins** [comment]
I think this should be resolved now, so I'll go ahead and close this ticket.
