### ISSUE TITLE
stylish-haskell invalid argument

### ISSUE THREAD

**Issue by meownoid** [carymrobbins/intellij-haskforce#293]
Idea: 2016.2.1
HaskForce: 0.3-beta.36
Stylish-haskell: from stackage's lts-6.11

I'm getting an error:

```shell
Haskell Tools
				Nonzero exit status (1) from command: /home/egor/.local/bin/stylish-haskell --version
				Process stderr: Invalid option `--version'
				Usage: stylish-haskell [FILENAME]
```

**Comment by carymrobbins** [comment]
@meownoid - It seems that in newer versions of stylish-haskell the `--version` flag is now supported. See #283.
