### ISSUE TITLE
stylish-haskell

### ISSUE THREAD

**Issue by tolysz** [carymrobbins/intellij-haskforce#299]
`stylish-haskell` no longer has `--version` 

    Haskell Tools
			Nonzero exit status (1) from command: /home/m/.local/bin/stylish-haskell --version
			Process stderr: Invalid option `--version'
			Usage: stylish-haskell [FILENAME]

however version can be recovered via `--help`

    >~/.local/bin/stylish-haskell --help
    stylish-haskell v0.5.17.0
    
    Usage: stylish-haskell [FILENAME]
    
    Available options:
      -h,--help                Show this help text
      -c,--config CONFIG       Configuration file
      -v,--verbose             Run in verbose mode
      -d,--defaults            Dump default config and exit
      -i,--inplace             Overwrite the given files in place
      --no-utf8                Don't force UTF-8 stdin/stdout
      FILENAME                 Input file(s)

**Comment by yawaramin** [comment]
It does as of https://github.com/jaspervdj/stylish-haskell/commit/9f04365e1412aaa0d835649e899aec4f01a497d8 ... which was part of the 0.6.0.0 release.

The current default implicit Stack resolver is `lts-6.15` (from `stack path`), which contains stylish-haskell-0.5.17.0 only.

So, one option is to make the latest nightly resolver the default (e.g. `nightly-2016-09-04`) and then reinstall GHC and the packages.

**Comment by tolysz** [comment]
Just saying... it is still there and the change is minimal i.e. `--version` -> `--help` and read 1st line...

    > stylish-haskell --help
    stylish-haskell 0.6.1.0
    
    Usage: stylish-haskell [FILENAME]
    
    Available options:
      -h,--help                Show this help text
      --version                Show version information
      -c,--config CONFIG       Configuration file
      -v,--verbose             Run in verbose mode
      -d,--defaults            Dump default config and exit
      -i,--inplace             Overwrite the given files in place
      --no-utf8                Don't force UTF-8 stdin/stdout
      FILENAME                 Input file(s)

**Comment by yawaramin** [comment]
If you have stylish-haskell-0.6.1.0, you should be OK; that version should support the `--version` flag.

**Comment by carymrobbins** [comment]
Thanks @yawaramin for pointing out the solution here.  If someone wants implement a fall back to parsing it from the `--help` text I'm fine with that.  It would need to be done as part of HaskellToolsConfigurable, namely the [Tool.updateVersion](https://github.com/carymrobbins/intellij-haskforce/blob/284772aa415be974795ce2ad93051118420beaef/src/com/haskforce/settings/HaskellToolsConfigurable.java#L192-L199) method.

**Comment by tolysz** [comment]
Ho about: https://github.com/carymrobbins/intellij-haskforce/pull/301

**Comment by tolysz** [comment]
Changes are merged
