### ISSUE TITLE
Error Java JDK isn't specified for module ..

### ISSUE THREAD

**Issue by pjonsson** [carymrobbins/intellij-haskforce#31]
Sometimes the cabal build does not rebuild anything, and we get the above error. Here's a console printout:
```verbatim
mac213:haskell-src-exts pj$ cabal build -j5
Building haskell-src-exts-1.15.0.1...
Preprocessing library haskell-src-exts-1.15.0.1...
In-place registering haskell-src-exts-1.15.0.1...
Preprocessing test suite 'test' for haskell-src-exts-1.15.0.1...
mac213:haskell-src-exts pj$ 
```

I'm not too worried about the error message, but the fact that it is signaled as an error is troublesome. Our primary mechanism for detecting errors are the return values from cabal, so maybe something is up with them.

**Comment by grguthrie** [comment]
I am just trying to learn how to use this - and I have a Cabal with one executable, which does get built and the .exe put into dist/build/, but I get this same error when trying to run it - do I have some configuration error, or is this a bug as above?

**Comment by carymrobbins** [comment]
@grguthrie: This is a strange error that I have seen before, but it's been quite a while.  If you are working on an open source project you could point me to it and possibly I may be able to reproduce and resolve the bug.

Otherwise, if you just want to get past it, a possible workaround might be to close the project and, from outside of IntelliJ, remove the IntelliJ project files, meaning the `.idea` directory and any `*.iml` files.  You could then regenerate the files by opening IntelliJ again and going to **File > New Project > Haskell** and set the **Project location** to the root directory of your project.

If you have more details on how to reproduce this please share.  The more specific, the better as it may provide clues as to what is going on.

**Comment by grguthrie** [comment]
Thanks. It is a very simple project - basically a "Hello World" demo to try this IDE for Haskell.
I tried your suggestion, but it did not seem to find the files (cabal, .hs), so I started a new project - and it complains:
Cannot start compiler: the SDK is not specified for module "PowerSet".
Specify the SDK at Project Structure dialog.

**Comment by grguthrie** [comment]
I started a new project. Added my test program Demo.hs, and a Main.hs that imports and calls a function in Demo. It seems to build OK, but how do I run it? The executable is in dist/build/Demo/Demo.exe, but run asks for a configuration, and if I chose Haskell Application, it doesn't seem to allow one to actually run (grayed out). I am not sure what is different now, or how to proceed.

**Comment by carymrobbins** [comment]
@grguthrie: This sounds like a slightly different topic, so let's move the discussion over to #128 to keep it relevant.

**Comment by grguthrie** [comment]
Yes, thanks.

**Comment by grguthrie** [comment]
Yes, thank you.

-------------------------------------------
Gregory Guthrie
-------------------------------------------

**Comment by teozkr** [comment]
Suddenly came across this issue again. No repro, but restarting IntelliJ seems to have fixed it. IntelliJ IDEA Ultimate 14.1.4, HaskForce 0.3-beta.21.

**Comment by psfblair** [comment]
I've just seen this issue this morning with a project that was building fine last night. The only thing that's different besides code changes are that I added a symlink in the project directory pointing somewhere outside the project. Closing and reopening the project then caused the error to go away.

**Comment by carymrobbins** [comment]
The latest release now uses a dummy SDK, relying on the build tool configurations (stack, cabal, ghc).  This _should_ be a non-issue.  If anyone encounters this, please reopen this issue.

**Comment by runeksvendsen** [comment]
I'm seeing this issue consistently:

`Error:java: JDK isn't specified for module 'bitcoin-payment-channel'`

after successful builds (if I do `stack build` in a terminal after I see this error it always returns immediately, indicating that everything's built).

So I think the error may have something to do with IntelliJ trying to run the now built executable, in the build process, but the error message doesn't exactly say that.
