### ISSUE TITLE
Question :  running haskell with stack. Timepath ?

### ISSUE THREAD

**Issue by rwobben** [carymrobbins/intellij-haskforce#310]
Hello, 

I have read in the readme that at this moment I cannot run my project when I have installed stack.

Any idea when this is possible ? 

Second question :  Is there a way I can use ghci withhin this plugin or do I have to use a seperate window for it.

**Comment by carymrobbins** [comment]
You _can_ run stack applications, it seems we need to update the README. You just need to create a run configuration and choose **Haskell Stack Run** and follow the prompts.

For running ghci, you could open a terminal from within the IDE, but honestly, I generally prefer to run it in a separate terminal in full screen.
