### ISSUE TITLE
PhpStorm support

### ISSUE THREAD

**Issue by akazik** [carymrobbins/intellij-haskforce#313]
I'd really like PhpStorm support, is that possible?

I can install the plugin and it seems that highlighting works but there is no configuration.

**Comment by fycth** [comment]
I assume it's PhpStorm's limitation. Try to use IDEA Community Edition instead.

**Comment by akazik** [comment]
The CE worked. Thanks.

Maybe you should add to the [wiki](https://github.com/carymrobbins/intellij-haskforce/wiki/Quick-Start-Guide) that the CE also works fine.

P.S.: The Dependencies link has no content

**Comment by carymrobbins** [comment]
See ticket #65 for a discussion around integration with other Jetbrains products.

I'll go ahead and remove the broken dependencies link, thanks for the heads up!
