### ISSUE TITLE
Can't use ghc-mod as is

### ISSUE THREAD

**Issue by orome** [carymrobbins/intellij-haskforce#316]
When I launch InteliJ IDEA I get:

> Attempting to use a ghc-mod compiled with a different version of ghc: GHC version: '8.0.1.20161213' ghc-mod compiled with ghc version: '8.0.1' Please reconfigure ghc-mod to use a version compiled with GHC 8.0.1.20161213

I don't know how to proceed!

**Comment by carymrobbins** [comment]
Currently HaskForce prevents you from running ghc-mod with a ghc of a different version as this generally causes issues. This might be an example of a time when we might should provide an escape hatch as I'm not sure if ghc-mod would work fine in this case.

However, if you are using stack, the best way to use ghc-mod with your project is to build it for your project -

```
% cd path/to/your-project
% stack build ghc-mod
% stack exec -- which ghc-mod
/Users/orome/.stack/snapshots/x86_64-osx/lts-5.0/7.10.3/bin/ghc-mod
```

If you've already done this for your project's resolver version for another project then stack will just use the existing binary and won't need to rebuild.

**Comment by carymrobbins** [comment]
If this doesn't resolve the issue for you, feel free to hop on gitter and ping me.

**Comment by carymrobbins** [comment]
> I assume that I just install with Homebrew, and then never install any packages globally, just using stack as needed for each project. Correct?

That sounds about right. Sometimes it's convenient to have some tools available globally, but in general having them work on a per-project basis will keep things simple.

I think the following workflow should work for you -

```bash
# Install stack via your favorite package manager
% brew install haskell-stack
# You can upgrade stack anytime using its own `upgrade` command
% stack upgrade
# Now `cd` to your project
% cd path/to/your-project
# If your project does not have a stack.yaml, you'll need to create one. If it does, you
# don't need to run the `init` command
% stack init
# Now you should just be able to build your project
% stack build
# You can install additional tools local to the project with `build` as well. This will use the
# resolver version in `stack.yaml` to ensure that ghc-mod uses the same compiler and
# libraries as your project.
% stack build ghc-mod
# You can then locate the executable using the `which` command executed in the
# context of stack
% stack exec -- which ghc-mod
/Users/orome/.stack/snapshots/x86_64-osx/lts-5.0/7.10.3/bin/ghc-mod
```

There's also an `install` command, e.g. `stack install ghc-mod`; however, that
will install ghc-mod globally in `~/.local/bin` which is probably not what you want as
you'd probably end up back at square one with incompatible project ghc and ghc-mod compiler versions.

**Comment by orome** [comment]
Excellent thanks! 

I see what's missing: I need to enter the path to `/Users/orome/.stack/snapshots/x86_64-osx/lts-5.0/7.10.3/bin/ghc-mod` manually in the IDE config dialog, right?

**Comment by carymrobbins** [comment]
Yup, that should do it. Hopefully soon we'll provide support directly in HaskForce for managing all of this for you.

**Comment by orome** [comment]
Cool thanks!

Should I do the same (build locally under stack and explicitly link) for `ghc-modi`, `hlint`, and `stylish-haskell`?

And how do I get rid of the old system versions of these and `ghc-mod`? 

For that matter (I know I'm running on here, but you'll probably know better than most): how do I completely get rid of everything Haskell at the global level _except_ what `brew install haskell-stack` installs? Right now I seem to have a bunch of stuff lying around (e.g. old docsets, executables like  `ghc-mod` etc.) at the system level, even after [deleting all installed packages](http://stackoverflow.com/a/12048421/656912) with `rm -r ~/.ghc`.

**Comment by carymrobbins** [comment]
Honestly, if you're using stack, you shouldn't have to worry about it. If you really want to though, you'd just need to look at each installation and see how you've installed things. It looks like your ghc was installed with brew, so you'd want to use brew to uninstall it. But again, that seems like a lot of work for not much gain. Just use stack and all (err..umm..most) of your problems should go away.

**Comment by orome** [comment]
Cool. I can probably just wipe things out with `rm` and reinstall them if they're missing (esp. since stack is "protecting" me). In any case I gather I can just `stack build ...` to mask any lingering system junk, correct?

Finally, what's the correct way for a stack-based approach to build, test, and distribute to Hackage. That is: how should I be invoking cabal. Using just `cabal ...` ends up using the system stuff. Is there a way to ensure cabal is running under my local stack? (Sorry for the dumb questions.)

**Comment by carymrobbins** [comment]
I don't think you should be using the `cabal` (aka `cabal-install`) tool for anything. Stack uses the `Cabal` library under the hood, but that's about it.

Stack uses [Stackage](https://www.stackage.org/) as an improvement over Hackage. I haven't personally distributed anything to stackage, so I'd start by reading the [excellect stack documentation](https://docs.haskellstack.org/en/stable/README/) as I'd mostly be guessing. It might also be worthwhile to jump on the `#haskell-stack` channel on IRC Freenode to pose questions to the stack experts.

**Comment by orome** [comment]
I think Stackage depends on things being uploaded to Hackage first.

**Comment by carymrobbins** [comment]
Yeah, I'd just check with the stack guys (and read the docs) to see how you should go about that as I'm not really sure.

**Comment by orome** [comment]
Sorry for the follow up, but I have a question about the [instructions above](https://github.com/carymrobbins/intellij-haskforce/issues/316#issuecomment-269494693):

```
% cd path/to/your-project
% stack build ghc-mod
```

Doesn't this have the significant side effect of changing the Haskell installation for the entire project? Specifically, it adds a lot of packages not specified in the requirements for the package, so that testing the package in this sandbox is no longer a valid test of whether the specification for the package is sufficient?

Put another way: isn't it better to put ghc-mod in _some other place altogether_ (perhaps even at the system level) but anywhere will do (e.g. a 'dev support' sandbox)?

**Comment by carymrobbins** [comment]
My understanding is that your project doesn't get its own sandbox; the sandbox is actually determined by the `resolver` listed in `stack.yaml`. So any project that uses that `resolver` will use the same "sandbox". This is actually a great thing since we don't want to have to recompile the same dependencies multiple times if we can help it.

You _could_ compile ghc-mod from source to achieve what you're after, then point to the appropriate version, but that seems complicated and I'm skeptical that you'd be gaining anything. Your Haskell installation might require some system dependency not captured by stack nor cabal, so to ensure that your build is reproducible it's best to use some sort of CI.

Although, I'm also skeptical that `stack build ghc-mod` would break your build somehow. The idea behind stack is that all of the packages in a stackage release are compatible with one another, so you should be fine. If some problem does occur, I'd file a bug with stack.

Also, `stack build ghc-mod` doesn't add requirements to your project's `stack.yaml` nor `.cabal` file, so there really shouldn't be any side-effects to speak of. Cabal should enforce that you have the appropriate dependencies explicitly listed, so if you are concerned about transitive dependencies of ghc-mod accidentally being utilized, that shouldn't be an issue either.

**Comment by orome** [comment]
So just to be clear `stack build ghc-mod` isn't added to the sandbox used by my project (e.g, when I test experiment with it using`stack ghci` or test it with `stack test`)? Or is it?

**Comment by carymrobbins** [comment]
There is no project sandbox to speak of other than your resolver, which will be used across any projects using that resolver version. Compiling, testing, and ghci should not be able to access ghc-mod libraries unless you've explicitly listed them in stack.yaml or your .cabal file. Running `stack build` just builds it for the project's resolver.

**Comment by orome** [comment]
[I think I see now.](http://stackoverflow.com/a/41399332/656912) My confusion came from the fact that the `ghc-mod` _executable_ sticks around, which make me incorrectly conclude that the corresponding package would also be seen by `stack build` for my project..
