### ISSUE TITLE
Operators inside do-blocks are considered as syntax errors if they are on the same indentation level

### ISSUE THREAD

**Issue by ShrykeWindgrace** [carymrobbins/intellij-haskforce#333]
If an operator is inside a do-block is on the same indentation level, then this operator is considered to be a syntax error. If I increase the indentation level, the error flag goes away. Both versions are correct from the compiler's point of view. Reproducible with, e.g., Parsec and its `<?>` operator; MWE in the screenshots below.
![capture](https://user-images.githubusercontent.com/6421233/29454734-8ef60ce8-840e-11e7-9bb6-399610e63cb8.PNG)

![capture2](https://user-images.githubusercontent.com/6421233/29454735-8ef74b9e-840e-11e7-94d1-b5268b7b4011.PNG)

    module Test where

    import           Text.Parsec
    import           Text.Parsec.String

    testParser :: Parser Char
    testParser = do
        c <- char 'c'
        <?> "char c expected"

**Comment by carymrobbins** [comment]
Thanks for the report @ShrykeWindgrace, the fix has been merged to master. It will be included in the `0.3.39` release.

**Comment by ShrykeWindgrace** [comment]
Thank you @carymrobbins for such a quick fix!

**Comment by carymrobbins** [comment]
No problem! I'm trying to get a couple of over things in before the next release. Do you need me to cut a snapshot build for you, or are you ok with building from source in the meantime?

**Comment by ShrykeWindgrace** [comment]
Don't worry, I'll build from source=) Cheers!
