### ISSUE TITLE
HaskForce should use the Scala 2.12 runtime

### ISSUE THREAD

**Issue by mcastse** [carymrobbins/intellij-haskforce#348]
Even using the latest plugin, version 0.3.40, I always get

Error:Module 'Small17' tests: java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V

when trying to compile a project (here called 'Small17'). What has scala got to do with it anyway?
I also note there are no tests enabled or even available.

**Comment by mcastse** [comment]
I note that the presence of the HaskForce plugin is enough to prevent scala projects from compiling. I have has to uninstall and am now without a Haskell IDE.

**Comment by carymrobbins** [comment]
@mcastse Did you intend to close the issue? Reopening just in case.

What version of the Scala plugin are you using? HaskForce actually is implemented partially in Scala, so maybe between the Scala and HaskForce plugins there are classpath issues resolving the scala jars bundled in the plugin archive. I also use the Scala plugin but do not encounter this issue.

**Comment by mcastse** [comment]
No, I did not intend to close the issue. I simply meant to add a comment that I could not use the Scala plugin without removing HaskForce. The version of the Scala plugin being used is “2017.3.193”. This is a nightly version which I was asked to use after reporting an issue that this one is supposed to cure.
The installed system version of Scala is 2.12.3 although several other versions are available following experimentation with SBT (which I did not like at all).
I case it makes any difference:
I have been unable to get a Scala 2.13 pre-release to work – the entry point of a program goes missing.
JDK 1.8 is the installed system default. I can also use JDK 9 (although not with Scala) but I cannot run the installer, only unpack the files it contains using 7zip.
I am using the latest Haskell Platform with appropriate updates (for hlint etc.).
All this is 32-bit software on a 64-bit machine because of browser requirements.

**Comment by carymrobbins** [comment]
Just to tie the loop on this, we may need a separate build of HaskForce that is compatible with the Scala plugin running Scala >=2.12. This could be accomplished in an adhoc way be removing the dependency on the scala libraries from the build.gradle and instead adding the Scala plugin as a dependency, something like -

```groovy
intellij {
  plugins = ['Scala']
}
```

However, we may also need to dynamically add the appropriate scala jars to the builder classpath.

**Comment by mcastse** [comment]
Thanks for the update. However, there is another issue, beyond your control, namely that the latest Haskell Platform (8.2.1), or at least the ghc/cabal that it provides, cannot install ghc-mod ☹

**Comment by niktrop** [comment]
I'm going to add a notification about plugins incompatibility for now. It will just check if HaskForce plugin uses scala 2.11 and suggest to disable one of the plugins:
![image](https://user-images.githubusercontent.com/3604749/33568245-de46c13e-d936-11e7-8c6d-4e200e05f34e.png)

**Comment by carymrobbins** [comment]
@niktrop Oh that's great, I'll try to keep in mind that we're able to do this and look out for other plugins which may be incompatible with HaskForce.

**Comment by jastice** [comment]
For reference, ticket on Scala Plugin tracker: https://youtrack.jetbrains.com/issue/SCL-12563

**Comment by carymrobbins** [comment]
@niktrop Oh that's great, I'll try to keep in mind that we're able to do this and look out for other plugins which may be incompatible with HaskForce.

**Comment by carymrobbins** [comment]
I've released v0.3.41 which now uses the Scala 2.12 runtime, so this issue no longer persists. Please let me know if you run into other problems!
