### ISSUE TITLE
HaskForce plugin is not compatible with Scala plugin in IntelliJ 2017.3

### ISSUE THREAD

**Issue by wigahluk** [carymrobbins/intellij-haskforce#351]
Hello,

I just upgraded IntelliJ to 2017.3 version and was forced to disable one of the two plugins as IntelliJ complains that Scala and HaskForce are not compatible.

I'm running MacOS HIghSierra 10.13.1
IntelliJ: 2017.3 Build #IU-173.3727.127
Mac OS X 10.13.1
HaskForce Plugin: 0.3.40
Scala Plugin: 2017.3.10

**Comment by abdmob** [comment]
I think this is linked to https://github.com/carymrobbins/intellij-haskforce/issues/348
I had to disable HaskForce plugin for now :( 
any working workarounds?

**Comment by carymrobbins** [comment]
I've released v0.3.41 which now uses the Scala 2.12 runtime, so upgrading to the latest version should resolve the issue. Let me know if you encounter any other problems!
