### ISSUE TITLE
HLint integration not appear.

### ISSUE THREAD

**Issue by 0x11901** [carymrobbins/intellij-haskforce#365]
I've seen hlint with haskforce like this:

![hlint](http://ooph3gs8p.bkt.clouddn.com/hlint.gif)

but I can not see the highlight in my turn, hlint works well from haskell tools console.

![demo6](http://ooph3gs8p.bkt.clouddn.com/demo6.gif)

---

IntelliJ IDEA 2018.1.5 (Ultimate Edition)
Build #IU-181.5281.24, built on June 12, 2018
JRE: 1.8.0_152-release-1136-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.5

---

HLint v2.1.5, (C) Neil Mitchell 2006-2018

**Comment by carymrobbins** [comment]
@0x11901 Seems this was a breaking change with HLint. I've just merged a fix for this, it should be available in the v0.3.42 release.
