### ISSUE TITLE
Failed ghc-mod errors should print failed command line

### ISSUE THREAD

**Issue by laura-dietz** [carymrobbins/intellij-haskforce#369]
Currently debugging Haskforce when something fails is rather painful. For instance, currently you might get an error like,
```
3:09 PM	Type Info Error
					There was an error when executing the ghc-modi `type` command:
					Loaded package environment from /home/dietz/trec-car/code/mediawiki-annotate/.ghc.environment.x86_64-linux-8.4.3
					93 5 93 17 "FilePath -> Data.Text.Internal.Lazy.Text -> IO ()"
					93 5 93 23 "Data.Text.Internal.Lazy.Text -> IO ()"
					93 5 94 30 "IO ()"
					92 1 103 10 "FilePath -> [Entry QueryId DocumentName rel] -> IO ()"
					Configure
```

But it's very hard to know what *actually* failed. Adding the failed command line to this message would be very helpful.

**Comment by carymrobbins** [comment]
@laura-dietz Check the Haskell Tools Console; it should contain the command and the error message. However, I think there's an argument to having it in the notification as well.

**Comment by laura-dietz** [comment]
@carymrobbins Where can I find the "Haskell Tools Console"?  In the tools menu I only have a JShell/Python Console.

So far, I only looked at the Event Log.   Thanks much!

**Comment by carymrobbins** [comment]
Check here - https://github.com/carymrobbins/intellij-haskforce/wiki/Quick-Start-Guide#haskell-tools-console

Let me know if that doesn't help or if you encounter issues.

**Comment by laura-dietz** [comment]
Ok, got it. I first needed to create a haskell module and restart idea for the Haskell Tools Console to become available in the IDE.

Thanks for the great tool!

**Comment by carymrobbins** [comment]
How did you create the project? Wondering why the Haskell module didn't already exist.
