### ISSUE TITLE
Plugin doesn't work with IDEA 2019.3 EAP

### ISSUE THREAD

**Issue by niktrop** [carymrobbins/intellij-haskforce#407]
Latest version 0.3.43 is compatible only with 2019.2.

**Comment by carymrobbins** [comment]
Do you get an exception stack trace?

**Comment by niktrop** [comment]
See the log attached:
[idea.log](https://github.com/carymrobbins/intellij-haskforce/files/3789000/idea.log)

0.3.42 is downloaded from the plugin repository because it is the latest without `until-build`.

**Comment by telebin** [comment]
I'm not sure if my problem is related to this one ("doesn't work" is quite general statement) but installation of this plugin broke indexing Java classes (in Gradle and Maven managed projects alike). Indexing of Ruby and Python classes still work fine. Unfortunately I didn't use previous versions of this plugin nor I didn't use it on previous versions of IDEA, so I don't know whether it worked before (hence my commenting in this issue instead creating new one)

[idea.log](https://github.com/carymrobbins/intellij-haskforce/files/3943779/idea.log)

**Comment by OmanF** [comment]
No longer 2019.3 EAP but the _full-blown thing_.
Also, _plugin version 0.3.42_ (didn't even get an update message when checking for updates), installed from IntelliJ's internal plugin manager.

[idea.log](https://github.com/carymrobbins/intellij-haskforce/files/3948675/idea.log)

**Comment by carymrobbins** [comment]
I've cut a pre-release which includes a fix for this issue - [v0.3.44-SNAPSHOT-28a838b9](https://github.com/carymrobbins/intellij-haskforce/releases/tag/v0.3.44-SNAPSHOT-28a838b9)
