### ISSUE TITLE
Not working with rainbow brackets plugin

### ISSUE THREAD

**Issue by dima74** [carymrobbins/intellij-haskforce#413]
All brackets have yellow color, when using [rainbow brackets plugin](https://github.com/izhangzhihao/intellij-rainbow-brackets):

![image](https://user-images.githubusercontent.com/6505554/70864613-caede380-1f64-11ea-90d5-1d06b8f41c25.png)

It is likely because expressions have flat structure, thus preventing rainbow brackets plugin from finding matched brackets. Screenshot with PSIViewer plugin:

![image](https://user-images.githubusercontent.com/6505554/70864835-67b18080-1f67-11ea-86d0-0005341cae59.png)

**Comment by izhangzhihao** [comment]
Related to https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/374

**Comment by izhangzhihao** [comment]
@dima74 maybe you should report this issue to https://github.com/rikvdkleij/intellij-haskell

**Comment by carymrobbins** [comment]
@izhangzhihao Nice catch. I'll go ahead and close this for now unless someone has an issue with this in HaskForce.

**Comment by dima74** [comment]
I am really sorry for providing incorrect information. Now reported this issue to IntelliJ-Haskell.
