### ISSUE TITLE
Error checking doesn't support multiple cabal components

### ISSUE THREAD

**Issue by sideeffffect** [carymrobbins/intellij-haskforce#61]
`derive` in `derive makeArbitrary ''Term` gets underlined

![image](https://cloud.githubusercontent.com/assets/9019485/4605979/0daab29c-5207-11e4-8ed5-9a1159117d32.png)

if this doesn't provide enough info, I can make a minimal project where this error professes

**Comment by carymrobbins** [comment]
ghc-mod should now support this, please reopen if this issue persists.
