### ISSUE TITLE
Support Rank-N types in syntax

### ISSUE THREAD

**Issue by bmjames** [carymrobbins/intellij-haskforce#92]
The GHC `RankNTypes` extension is used fairly commonly, and it would be great if it was supported. Currently, the parser doesn't support syntax like this, which is valid with `RankNTypes`:

![image](https://cloud.githubusercontent.com/assets/21567/5283912/a491f718-7b08-11e4-9863-155e52623358.png)

**Comment by carymrobbins** [comment]
@bmjames - This one should be resolved as well.  I'll close this issue once the latest release is out.
